spring:
  application:
    name: gateway-api
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:9000
      username: root
      password: s3cr3t
      name: global, gateway-api
      profile: default