spring:
  application:
    name: service-uaa

grpc:
  server:
    port: ${GRPC_SERVER_PORT:12080}
#  client:
#    registration:
#      address: ${GRPC_CLIENT_REGISTRATION_HOST_PORT:static://localhost:12050}
#      negotiationType: plaintext

server:
  port: ${REST_SERVER_PORT:9299}