// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package dr.app.core.autogen.grpc.common;

public interface ErrorListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.ErrorList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .common.Error errors = 1;</code>
   */
  java.util.List<dr.app.core.autogen.grpc.common.Error> 
      getErrorsList();
  /**
   * <code>repeated .common.Error errors = 1;</code>
   */
  dr.app.core.autogen.grpc.common.Error getErrors(int index);
  /**
   * <code>repeated .common.Error errors = 1;</code>
   */
  int getErrorsCount();
  /**
   * <code>repeated .common.Error errors = 1;</code>
   */
  java.util.List<? extends dr.app.core.autogen.grpc.common.ErrorOrBuilder> 
      getErrorsOrBuilderList();
  /**
   * <code>repeated .common.Error errors = 1;</code>
   */
  dr.app.core.autogen.grpc.common.ErrorOrBuilder getErrorsOrBuilder(
      int index);
}
