spring:
  application:
    name: service-registration
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:9000
      username: root
      password: s3cr3t
      name: global, service-registration
      profile: default