server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - StripPrefix=2
      routes:
        # service auth route
        - id: serviceAuth
          uri: lb://SERVICE-AUTH
          predicates:
            - Path=/api/auth/**
        # service gamification route
        - id: serviceGamification
          uri: lb://SERVICE-GAMIFICATION
          predicates:
            - Path=/api/gamification/**
        # service gamification route
        - id: serviceCalculator
          uri: lb://SERVICE-CALCULATOR
          predicates:
            - Path=/api/calculator/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    fetchRegistry: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management:
  endpoint.gateway.enabled: true # default value
  endpoints.web.exposure.include: gateway