server:
  port: 8000

spring:
  application:
    name: gateway

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    auth:
      path: /auth/**
      serviceId: service-auth
#      stripPrefix: true
    calculator:
      path: /calculator/**
      serviceId: service-calculator
    gamification:
      path: /gamification/**
      serviceId: service-gamification

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    fetchRegistry: true


---
# Adds admin routes for testing purposes
spring:
  profiles: test
zuul:
  routes:
    gamification-admin:
      path: /gamification/admin/**
      serviceId: service-gamification
      strip-prefix: false
    multiplication-admin:
      path: /multiplication/admin/**
      serviceId: service-calculator
      strip-prefix: false