server:
  port: 8020

## Spring configuration
spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_SERVER:localhost}:${MONGODB_SERVER_PORT:27017}/db_gamification
  rabbitmq:
    host: ${RABBITMQ_SERVER:localhost}
    username: user
    password: bitnami
    port: 5672
  application:
    name: service-gamification

## RabbitMQ configuration
multiplication:
  exchange: multiplication_exchange
  solved:
    key: multiplication.solved
  queue: gamification_multiplication_queue
  anything:
    routing-key: multiplication.*

# REST client settings
multiplicationHost: service-calculator
#multiplicationHost: http://localhost:8080

# Service Discovery configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

## Log configuration
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate=DEBUG: