// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attendance.proto

package dr.app.core.autogen.grpc.attendance;

/**
 * Protobuf enum {@code attendance.ATCheckType}
 */
public enum ATCheckType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CT_CLOCK = 0;</code>
   */
  CT_CLOCK(0),
  /**
   * <code>CT_EDIT = 1;</code>
   */
  CT_EDIT(1),
  /**
   * <code>CT_WEB = 2;</code>
   */
  CT_WEB(2),
  /**
   * <code>CT_MOBILE = 3;</code>
   */
  CT_MOBILE(3),
  /**
   * <code>CT_BEACON = 4;</code>
   */
  CT_BEACON(4),
  /**
   * <code>CT_DATA = 5;</code>
   */
  CT_DATA(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CT_CLOCK = 0;</code>
   */
  public static final int CT_CLOCK_VALUE = 0;
  /**
   * <code>CT_EDIT = 1;</code>
   */
  public static final int CT_EDIT_VALUE = 1;
  /**
   * <code>CT_WEB = 2;</code>
   */
  public static final int CT_WEB_VALUE = 2;
  /**
   * <code>CT_MOBILE = 3;</code>
   */
  public static final int CT_MOBILE_VALUE = 3;
  /**
   * <code>CT_BEACON = 4;</code>
   */
  public static final int CT_BEACON_VALUE = 4;
  /**
   * <code>CT_DATA = 5;</code>
   */
  public static final int CT_DATA_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ATCheckType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ATCheckType forNumber(int value) {
    switch (value) {
      case 0: return CT_CLOCK;
      case 1: return CT_EDIT;
      case 2: return CT_WEB;
      case 3: return CT_MOBILE;
      case 4: return CT_BEACON;
      case 5: return CT_DATA;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ATCheckType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ATCheckType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ATCheckType>() {
          public ATCheckType findValueByNumber(int number) {
            return ATCheckType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return dr.app.core.autogen.grpc.attendance.AttendanceOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final ATCheckType[] VALUES = values();

  public static ATCheckType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ATCheckType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:attendance.ATCheckType)
}

