// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attendance.proto

package dr.app.core.autogen.grpc.attendance;

public interface ATInputLogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:attendance.ATInputLogResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool todayFixCancel = 1;</code>
   * @return The todayFixCancel.
   */
  boolean getTodayFixCancel();

  /**
   * <code>string errorCode = 2;</code>
   * @return The errorCode.
   */
  java.lang.String getErrorCode();
  /**
   * <code>string errorCode = 2;</code>
   * @return The bytes for errorCode.
   */
  com.google.protobuf.ByteString
      getErrorCodeBytes();
}
