// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attendance.proto

package dr.app.core.autogen.grpc.attendance;

/**
 * Protobuf type {@code attendance.ATInputLog}
 */
public final class ATInputLog extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:attendance.ATInputLog)
    ATInputLogOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ATInputLog.newBuilder() to construct.
  private ATInputLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ATInputLog() {
    userId_ = "";
    officeUserId_ = "";
    checkType_ = 0;
    targetDate_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ATInputLog();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ATInputLog(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            officeUserId_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            checkType_ = rawValue;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            targetDate_ = s;
            break;
          }
          case 40: {

            dayMode_ = input.readInt32();
            break;
          }
          case 48: {

            sameDayConfirm_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dr.app.core.autogen.grpc.attendance.AttendanceOuterClass.internal_static_attendance_ATInputLog_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dr.app.core.autogen.grpc.attendance.AttendanceOuterClass.internal_static_attendance_ATInputLog_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dr.app.core.autogen.grpc.attendance.ATInputLog.class, dr.app.core.autogen.grpc.attendance.ATInputLog.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private volatile java.lang.Object userId_;
  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OFFICEUSERID_FIELD_NUMBER = 2;
  private volatile java.lang.Object officeUserId_;
  /**
   * <code>string officeUserId = 2;</code>
   * @return The officeUserId.
   */
  @java.lang.Override
  public java.lang.String getOfficeUserId() {
    java.lang.Object ref = officeUserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      officeUserId_ = s;
      return s;
    }
  }
  /**
   * <code>string officeUserId = 2;</code>
   * @return The bytes for officeUserId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOfficeUserIdBytes() {
    java.lang.Object ref = officeUserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      officeUserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHECKTYPE_FIELD_NUMBER = 3;
  private int checkType_;
  /**
   * <code>.attendance.ATCheckType checkType = 3;</code>
   * @return The enum numeric value on the wire for checkType.
   */
  @java.lang.Override public int getCheckTypeValue() {
    return checkType_;
  }
  /**
   * <code>.attendance.ATCheckType checkType = 3;</code>
   * @return The checkType.
   */
  @java.lang.Override public dr.app.core.autogen.grpc.attendance.ATCheckType getCheckType() {
    @SuppressWarnings("deprecation")
    dr.app.core.autogen.grpc.attendance.ATCheckType result = dr.app.core.autogen.grpc.attendance.ATCheckType.valueOf(checkType_);
    return result == null ? dr.app.core.autogen.grpc.attendance.ATCheckType.UNRECOGNIZED : result;
  }

  public static final int TARGETDATE_FIELD_NUMBER = 4;
  private volatile java.lang.Object targetDate_;
  /**
   * <code>string targetDate = 4;</code>
   * @return The targetDate.
   */
  @java.lang.Override
  public java.lang.String getTargetDate() {
    java.lang.Object ref = targetDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      targetDate_ = s;
      return s;
    }
  }
  /**
   * <code>string targetDate = 4;</code>
   * @return The bytes for targetDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTargetDateBytes() {
    java.lang.Object ref = targetDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      targetDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DAYMODE_FIELD_NUMBER = 5;
  private int dayMode_;
  /**
   * <code>int32 dayMode = 5;</code>
   * @return The dayMode.
   */
  @java.lang.Override
  public int getDayMode() {
    return dayMode_;
  }

  public static final int SAMEDAYCONFIRM_FIELD_NUMBER = 6;
  private boolean sameDayConfirm_;
  /**
   * <code>bool sameDayConfirm = 6;</code>
   * @return The sameDayConfirm.
   */
  @java.lang.Override
  public boolean getSameDayConfirm() {
    return sameDayConfirm_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(officeUserId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, officeUserId_);
    }
    if (checkType_ != dr.app.core.autogen.grpc.attendance.ATCheckType.CT_CLOCK.getNumber()) {
      output.writeEnum(3, checkType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetDate_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, targetDate_);
    }
    if (dayMode_ != 0) {
      output.writeInt32(5, dayMode_);
    }
    if (sameDayConfirm_ != false) {
      output.writeBool(6, sameDayConfirm_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(officeUserId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, officeUserId_);
    }
    if (checkType_ != dr.app.core.autogen.grpc.attendance.ATCheckType.CT_CLOCK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, checkType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetDate_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, targetDate_);
    }
    if (dayMode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, dayMode_);
    }
    if (sameDayConfirm_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, sameDayConfirm_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dr.app.core.autogen.grpc.attendance.ATInputLog)) {
      return super.equals(obj);
    }
    dr.app.core.autogen.grpc.attendance.ATInputLog other = (dr.app.core.autogen.grpc.attendance.ATInputLog) obj;

    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (!getOfficeUserId()
        .equals(other.getOfficeUserId())) return false;
    if (checkType_ != other.checkType_) return false;
    if (!getTargetDate()
        .equals(other.getTargetDate())) return false;
    if (getDayMode()
        != other.getDayMode()) return false;
    if (getSameDayConfirm()
        != other.getSameDayConfirm()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + OFFICEUSERID_FIELD_NUMBER;
    hash = (53 * hash) + getOfficeUserId().hashCode();
    hash = (37 * hash) + CHECKTYPE_FIELD_NUMBER;
    hash = (53 * hash) + checkType_;
    hash = (37 * hash) + TARGETDATE_FIELD_NUMBER;
    hash = (53 * hash) + getTargetDate().hashCode();
    hash = (37 * hash) + DAYMODE_FIELD_NUMBER;
    hash = (53 * hash) + getDayMode();
    hash = (37 * hash) + SAMEDAYCONFIRM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSameDayConfirm());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dr.app.core.autogen.grpc.attendance.ATInputLog parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.attendance.ATInputLog parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.attendance.ATInputLog parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.attendance.ATInputLog parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.attendance.ATInputLog parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.attendance.ATInputLog parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.attendance.ATInputLog parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.attendance.ATInputLog parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.attendance.ATInputLog parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.attendance.ATInputLog parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.attendance.ATInputLog parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.attendance.ATInputLog parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dr.app.core.autogen.grpc.attendance.ATInputLog prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code attendance.ATInputLog}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:attendance.ATInputLog)
      dr.app.core.autogen.grpc.attendance.ATInputLogOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dr.app.core.autogen.grpc.attendance.AttendanceOuterClass.internal_static_attendance_ATInputLog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dr.app.core.autogen.grpc.attendance.AttendanceOuterClass.internal_static_attendance_ATInputLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dr.app.core.autogen.grpc.attendance.ATInputLog.class, dr.app.core.autogen.grpc.attendance.ATInputLog.Builder.class);
    }

    // Construct using dr.app.core.autogen.grpc.attendance.ATInputLog.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userId_ = "";

      officeUserId_ = "";

      checkType_ = 0;

      targetDate_ = "";

      dayMode_ = 0;

      sameDayConfirm_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dr.app.core.autogen.grpc.attendance.AttendanceOuterClass.internal_static_attendance_ATInputLog_descriptor;
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.attendance.ATInputLog getDefaultInstanceForType() {
      return dr.app.core.autogen.grpc.attendance.ATInputLog.getDefaultInstance();
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.attendance.ATInputLog build() {
      dr.app.core.autogen.grpc.attendance.ATInputLog result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.attendance.ATInputLog buildPartial() {
      dr.app.core.autogen.grpc.attendance.ATInputLog result = new dr.app.core.autogen.grpc.attendance.ATInputLog(this);
      result.userId_ = userId_;
      result.officeUserId_ = officeUserId_;
      result.checkType_ = checkType_;
      result.targetDate_ = targetDate_;
      result.dayMode_ = dayMode_;
      result.sameDayConfirm_ = sameDayConfirm_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dr.app.core.autogen.grpc.attendance.ATInputLog) {
        return mergeFrom((dr.app.core.autogen.grpc.attendance.ATInputLog)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dr.app.core.autogen.grpc.attendance.ATInputLog other) {
      if (other == dr.app.core.autogen.grpc.attendance.ATInputLog.getDefaultInstance()) return this;
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (!other.getOfficeUserId().isEmpty()) {
        officeUserId_ = other.officeUserId_;
        onChanged();
      }
      if (other.checkType_ != 0) {
        setCheckTypeValue(other.getCheckTypeValue());
      }
      if (!other.getTargetDate().isEmpty()) {
        targetDate_ = other.targetDate_;
        onChanged();
      }
      if (other.getDayMode() != 0) {
        setDayMode(other.getDayMode());
      }
      if (other.getSameDayConfirm() != false) {
        setSameDayConfirm(other.getSameDayConfirm());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dr.app.core.autogen.grpc.attendance.ATInputLog parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dr.app.core.autogen.grpc.attendance.ATInputLog) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userId = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>string userId = 1;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object officeUserId_ = "";
    /**
     * <code>string officeUserId = 2;</code>
     * @return The officeUserId.
     */
    public java.lang.String getOfficeUserId() {
      java.lang.Object ref = officeUserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        officeUserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string officeUserId = 2;</code>
     * @return The bytes for officeUserId.
     */
    public com.google.protobuf.ByteString
        getOfficeUserIdBytes() {
      java.lang.Object ref = officeUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        officeUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string officeUserId = 2;</code>
     * @param value The officeUserId to set.
     * @return This builder for chaining.
     */
    public Builder setOfficeUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      officeUserId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string officeUserId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOfficeUserId() {
      
      officeUserId_ = getDefaultInstance().getOfficeUserId();
      onChanged();
      return this;
    }
    /**
     * <code>string officeUserId = 2;</code>
     * @param value The bytes for officeUserId to set.
     * @return This builder for chaining.
     */
    public Builder setOfficeUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      officeUserId_ = value;
      onChanged();
      return this;
    }

    private int checkType_ = 0;
    /**
     * <code>.attendance.ATCheckType checkType = 3;</code>
     * @return The enum numeric value on the wire for checkType.
     */
    @java.lang.Override public int getCheckTypeValue() {
      return checkType_;
    }
    /**
     * <code>.attendance.ATCheckType checkType = 3;</code>
     * @param value The enum numeric value on the wire for checkType to set.
     * @return This builder for chaining.
     */
    public Builder setCheckTypeValue(int value) {
      
      checkType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.attendance.ATCheckType checkType = 3;</code>
     * @return The checkType.
     */
    @java.lang.Override
    public dr.app.core.autogen.grpc.attendance.ATCheckType getCheckType() {
      @SuppressWarnings("deprecation")
      dr.app.core.autogen.grpc.attendance.ATCheckType result = dr.app.core.autogen.grpc.attendance.ATCheckType.valueOf(checkType_);
      return result == null ? dr.app.core.autogen.grpc.attendance.ATCheckType.UNRECOGNIZED : result;
    }
    /**
     * <code>.attendance.ATCheckType checkType = 3;</code>
     * @param value The checkType to set.
     * @return This builder for chaining.
     */
    public Builder setCheckType(dr.app.core.autogen.grpc.attendance.ATCheckType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      checkType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.attendance.ATCheckType checkType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCheckType() {
      
      checkType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object targetDate_ = "";
    /**
     * <code>string targetDate = 4;</code>
     * @return The targetDate.
     */
    public java.lang.String getTargetDate() {
      java.lang.Object ref = targetDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string targetDate = 4;</code>
     * @return The bytes for targetDate.
     */
    public com.google.protobuf.ByteString
        getTargetDateBytes() {
      java.lang.Object ref = targetDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string targetDate = 4;</code>
     * @param value The targetDate to set.
     * @return This builder for chaining.
     */
    public Builder setTargetDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      targetDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string targetDate = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetDate() {
      
      targetDate_ = getDefaultInstance().getTargetDate();
      onChanged();
      return this;
    }
    /**
     * <code>string targetDate = 4;</code>
     * @param value The bytes for targetDate to set.
     * @return This builder for chaining.
     */
    public Builder setTargetDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      targetDate_ = value;
      onChanged();
      return this;
    }

    private int dayMode_ ;
    /**
     * <code>int32 dayMode = 5;</code>
     * @return The dayMode.
     */
    @java.lang.Override
    public int getDayMode() {
      return dayMode_;
    }
    /**
     * <code>int32 dayMode = 5;</code>
     * @param value The dayMode to set.
     * @return This builder for chaining.
     */
    public Builder setDayMode(int value) {
      
      dayMode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 dayMode = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDayMode() {
      
      dayMode_ = 0;
      onChanged();
      return this;
    }

    private boolean sameDayConfirm_ ;
    /**
     * <code>bool sameDayConfirm = 6;</code>
     * @return The sameDayConfirm.
     */
    @java.lang.Override
    public boolean getSameDayConfirm() {
      return sameDayConfirm_;
    }
    /**
     * <code>bool sameDayConfirm = 6;</code>
     * @param value The sameDayConfirm to set.
     * @return This builder for chaining.
     */
    public Builder setSameDayConfirm(boolean value) {
      
      sameDayConfirm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool sameDayConfirm = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSameDayConfirm() {
      
      sameDayConfirm_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:attendance.ATInputLog)
  }

  // @@protoc_insertion_point(class_scope:attendance.ATInputLog)
  private static final dr.app.core.autogen.grpc.attendance.ATInputLog DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dr.app.core.autogen.grpc.attendance.ATInputLog();
  }

  public static dr.app.core.autogen.grpc.attendance.ATInputLog getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ATInputLog>
      PARSER = new com.google.protobuf.AbstractParser<ATInputLog>() {
    @java.lang.Override
    public ATInputLog parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ATInputLog(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ATInputLog> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ATInputLog> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dr.app.core.autogen.grpc.attendance.ATInputLog getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

