// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration.proto

package dr.app.core.autogen.grpc.registration;

/**
 * Protobuf type {@code registration.REBeaconAttendanceArea}
 */
public final class REBeaconAttendanceArea extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:registration.REBeaconAttendanceArea)
    REBeaconAttendanceAreaOrBuilder {
private static final long serialVersionUID = 0L;
  // Use REBeaconAttendanceArea.newBuilder() to construct.
  private REBeaconAttendanceArea(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private REBeaconAttendanceArea() {
    id_ = "";
    name_ = "";
    defaultStayReason_ = 0;
    officeId_ = "";
    beaconType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new REBeaconAttendanceArea();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private REBeaconAttendanceArea(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            defaultStayReason_ = rawValue;
            break;
          }
          case 32: {

            color_ = input.readInt32();
            break;
          }
          case 40: {

            linkedBeaconCount_ = input.readInt64();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            officeId_ = s;
            break;
          }
          case 56: {
            int rawValue = input.readEnum();

            beaconType_ = rawValue;
            break;
          }
          case 64: {

            deleted_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.internal_static_registration_REBeaconAttendanceArea_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.internal_static_registration_REBeaconAttendanceArea_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea.class, dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   *&#47; ビーコン勤怠エリアコレクションのオブジェクトID
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; ビーコン勤怠エリアコレクションのオブジェクトID
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   *&#47; エリア名
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; エリア名
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEFAULTSTAYREASON_FIELD_NUMBER = 3;
  private int defaultStayReason_;
  /**
   * <pre>
   *&#47; デフォルトの滞在理由
   * </pre>
   *
   * <code>.registration.REDefaultStayReason defaultStayReason = 3;</code>
   * @return The enum numeric value on the wire for defaultStayReason.
   */
  @java.lang.Override public int getDefaultStayReasonValue() {
    return defaultStayReason_;
  }
  /**
   * <pre>
   *&#47; デフォルトの滞在理由
   * </pre>
   *
   * <code>.registration.REDefaultStayReason defaultStayReason = 3;</code>
   * @return The defaultStayReason.
   */
  @java.lang.Override public dr.app.core.autogen.grpc.registration.REDefaultStayReason getDefaultStayReason() {
    @SuppressWarnings("deprecation")
    dr.app.core.autogen.grpc.registration.REDefaultStayReason result = dr.app.core.autogen.grpc.registration.REDefaultStayReason.valueOf(defaultStayReason_);
    return result == null ? dr.app.core.autogen.grpc.registration.REDefaultStayReason.UNRECOGNIZED : result;
  }

  public static final int COLOR_FIELD_NUMBER = 4;
  private int color_;
  /**
   * <pre>
   *&#47; 表示色
   * </pre>
   *
   * <code>int32 color = 4;</code>
   * @return The color.
   */
  @java.lang.Override
  public int getColor() {
    return color_;
  }

  public static final int LINKEDBEACONCOUNT_FIELD_NUMBER = 5;
  private long linkedBeaconCount_;
  /**
   * <pre>
   *&#47; エリアに紐づいたビーコンの数
   * </pre>
   *
   * <code>int64 linkedBeaconCount = 5;</code>
   * @return The linkedBeaconCount.
   */
  @java.lang.Override
  public long getLinkedBeaconCount() {
    return linkedBeaconCount_;
  }

  public static final int OFFICEID_FIELD_NUMBER = 6;
  private volatile java.lang.Object officeId_;
  /**
   * <pre>
   *&#47; 事業所ID
   * </pre>
   *
   * <code>string officeId = 6;</code>
   * @return The officeId.
   */
  @java.lang.Override
  public java.lang.String getOfficeId() {
    java.lang.Object ref = officeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      officeId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; 事業所ID
   * </pre>
   *
   * <code>string officeId = 6;</code>
   * @return The bytes for officeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOfficeIdBytes() {
    java.lang.Object ref = officeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      officeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BEACONTYPE_FIELD_NUMBER = 7;
  private int beaconType_;
  /**
   * <pre>
   *&#47; ビーコン導入種別
   * </pre>
   *
   * <code>.registration.REBeaconType beaconType = 7;</code>
   * @return The enum numeric value on the wire for beaconType.
   */
  @java.lang.Override public int getBeaconTypeValue() {
    return beaconType_;
  }
  /**
   * <pre>
   *&#47; ビーコン導入種別
   * </pre>
   *
   * <code>.registration.REBeaconType beaconType = 7;</code>
   * @return The beaconType.
   */
  @java.lang.Override public dr.app.core.autogen.grpc.registration.REBeaconType getBeaconType() {
    @SuppressWarnings("deprecation")
    dr.app.core.autogen.grpc.registration.REBeaconType result = dr.app.core.autogen.grpc.registration.REBeaconType.valueOf(beaconType_);
    return result == null ? dr.app.core.autogen.grpc.registration.REBeaconType.UNRECOGNIZED : result;
  }

  public static final int DELETED_FIELD_NUMBER = 8;
  private boolean deleted_;
  /**
   * <pre>
   *&#47; 削除済フラグ
   * </pre>
   *
   * <code>bool deleted = 8;</code>
   * @return The deleted.
   */
  @java.lang.Override
  public boolean getDeleted() {
    return deleted_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (defaultStayReason_ != dr.app.core.autogen.grpc.registration.REDefaultStayReason.WORK.getNumber()) {
      output.writeEnum(3, defaultStayReason_);
    }
    if (color_ != 0) {
      output.writeInt32(4, color_);
    }
    if (linkedBeaconCount_ != 0L) {
      output.writeInt64(5, linkedBeaconCount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(officeId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, officeId_);
    }
    if (beaconType_ != dr.app.core.autogen.grpc.registration.REBeaconType.DRJOY.getNumber()) {
      output.writeEnum(7, beaconType_);
    }
    if (deleted_ != false) {
      output.writeBool(8, deleted_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (defaultStayReason_ != dr.app.core.autogen.grpc.registration.REDefaultStayReason.WORK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, defaultStayReason_);
    }
    if (color_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, color_);
    }
    if (linkedBeaconCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, linkedBeaconCount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(officeId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, officeId_);
    }
    if (beaconType_ != dr.app.core.autogen.grpc.registration.REBeaconType.DRJOY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, beaconType_);
    }
    if (deleted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, deleted_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea)) {
      return super.equals(obj);
    }
    dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea other = (dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (defaultStayReason_ != other.defaultStayReason_) return false;
    if (getColor()
        != other.getColor()) return false;
    if (getLinkedBeaconCount()
        != other.getLinkedBeaconCount()) return false;
    if (!getOfficeId()
        .equals(other.getOfficeId())) return false;
    if (beaconType_ != other.beaconType_) return false;
    if (getDeleted()
        != other.getDeleted()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DEFAULTSTAYREASON_FIELD_NUMBER;
    hash = (53 * hash) + defaultStayReason_;
    hash = (37 * hash) + COLOR_FIELD_NUMBER;
    hash = (53 * hash) + getColor();
    hash = (37 * hash) + LINKEDBEACONCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLinkedBeaconCount());
    hash = (37 * hash) + OFFICEID_FIELD_NUMBER;
    hash = (53 * hash) + getOfficeId().hashCode();
    hash = (37 * hash) + BEACONTYPE_FIELD_NUMBER;
    hash = (53 * hash) + beaconType_;
    hash = (37 * hash) + DELETED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDeleted());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code registration.REBeaconAttendanceArea}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:registration.REBeaconAttendanceArea)
      dr.app.core.autogen.grpc.registration.REBeaconAttendanceAreaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.internal_static_registration_REBeaconAttendanceArea_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.internal_static_registration_REBeaconAttendanceArea_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea.class, dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea.Builder.class);
    }

    // Construct using dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      name_ = "";

      defaultStayReason_ = 0;

      color_ = 0;

      linkedBeaconCount_ = 0L;

      officeId_ = "";

      beaconType_ = 0;

      deleted_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.internal_static_registration_REBeaconAttendanceArea_descriptor;
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea getDefaultInstanceForType() {
      return dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea.getDefaultInstance();
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea build() {
      dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea buildPartial() {
      dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea result = new dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea(this);
      result.id_ = id_;
      result.name_ = name_;
      result.defaultStayReason_ = defaultStayReason_;
      result.color_ = color_;
      result.linkedBeaconCount_ = linkedBeaconCount_;
      result.officeId_ = officeId_;
      result.beaconType_ = beaconType_;
      result.deleted_ = deleted_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea) {
        return mergeFrom((dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea other) {
      if (other == dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.defaultStayReason_ != 0) {
        setDefaultStayReasonValue(other.getDefaultStayReasonValue());
      }
      if (other.getColor() != 0) {
        setColor(other.getColor());
      }
      if (other.getLinkedBeaconCount() != 0L) {
        setLinkedBeaconCount(other.getLinkedBeaconCount());
      }
      if (!other.getOfficeId().isEmpty()) {
        officeId_ = other.officeId_;
        onChanged();
      }
      if (other.beaconType_ != 0) {
        setBeaconTypeValue(other.getBeaconTypeValue());
      }
      if (other.getDeleted() != false) {
        setDeleted(other.getDeleted());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <pre>
     *&#47; ビーコン勤怠エリアコレクションのオブジェクトID
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; ビーコン勤怠エリアコレクションのオブジェクトID
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; ビーコン勤怠エリアコレクションのオブジェクトID
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ビーコン勤怠エリアコレクションのオブジェクトID
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ビーコン勤怠エリアコレクションのオブジェクトID
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *&#47; エリア名
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; エリア名
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; エリア名
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; エリア名
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; エリア名
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int defaultStayReason_ = 0;
    /**
     * <pre>
     *&#47; デフォルトの滞在理由
     * </pre>
     *
     * <code>.registration.REDefaultStayReason defaultStayReason = 3;</code>
     * @return The enum numeric value on the wire for defaultStayReason.
     */
    @java.lang.Override public int getDefaultStayReasonValue() {
      return defaultStayReason_;
    }
    /**
     * <pre>
     *&#47; デフォルトの滞在理由
     * </pre>
     *
     * <code>.registration.REDefaultStayReason defaultStayReason = 3;</code>
     * @param value The enum numeric value on the wire for defaultStayReason to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultStayReasonValue(int value) {
      
      defaultStayReason_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; デフォルトの滞在理由
     * </pre>
     *
     * <code>.registration.REDefaultStayReason defaultStayReason = 3;</code>
     * @return The defaultStayReason.
     */
    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REDefaultStayReason getDefaultStayReason() {
      @SuppressWarnings("deprecation")
      dr.app.core.autogen.grpc.registration.REDefaultStayReason result = dr.app.core.autogen.grpc.registration.REDefaultStayReason.valueOf(defaultStayReason_);
      return result == null ? dr.app.core.autogen.grpc.registration.REDefaultStayReason.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *&#47; デフォルトの滞在理由
     * </pre>
     *
     * <code>.registration.REDefaultStayReason defaultStayReason = 3;</code>
     * @param value The defaultStayReason to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultStayReason(dr.app.core.autogen.grpc.registration.REDefaultStayReason value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      defaultStayReason_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; デフォルトの滞在理由
     * </pre>
     *
     * <code>.registration.REDefaultStayReason defaultStayReason = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDefaultStayReason() {
      
      defaultStayReason_ = 0;
      onChanged();
      return this;
    }

    private int color_ ;
    /**
     * <pre>
     *&#47; 表示色
     * </pre>
     *
     * <code>int32 color = 4;</code>
     * @return The color.
     */
    @java.lang.Override
    public int getColor() {
      return color_;
    }
    /**
     * <pre>
     *&#47; 表示色
     * </pre>
     *
     * <code>int32 color = 4;</code>
     * @param value The color to set.
     * @return This builder for chaining.
     */
    public Builder setColor(int value) {
      
      color_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 表示色
     * </pre>
     *
     * <code>int32 color = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearColor() {
      
      color_ = 0;
      onChanged();
      return this;
    }

    private long linkedBeaconCount_ ;
    /**
     * <pre>
     *&#47; エリアに紐づいたビーコンの数
     * </pre>
     *
     * <code>int64 linkedBeaconCount = 5;</code>
     * @return The linkedBeaconCount.
     */
    @java.lang.Override
    public long getLinkedBeaconCount() {
      return linkedBeaconCount_;
    }
    /**
     * <pre>
     *&#47; エリアに紐づいたビーコンの数
     * </pre>
     *
     * <code>int64 linkedBeaconCount = 5;</code>
     * @param value The linkedBeaconCount to set.
     * @return This builder for chaining.
     */
    public Builder setLinkedBeaconCount(long value) {
      
      linkedBeaconCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; エリアに紐づいたビーコンの数
     * </pre>
     *
     * <code>int64 linkedBeaconCount = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLinkedBeaconCount() {
      
      linkedBeaconCount_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object officeId_ = "";
    /**
     * <pre>
     *&#47; 事業所ID
     * </pre>
     *
     * <code>string officeId = 6;</code>
     * @return The officeId.
     */
    public java.lang.String getOfficeId() {
      java.lang.Object ref = officeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        officeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; 事業所ID
     * </pre>
     *
     * <code>string officeId = 6;</code>
     * @return The bytes for officeId.
     */
    public com.google.protobuf.ByteString
        getOfficeIdBytes() {
      java.lang.Object ref = officeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        officeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; 事業所ID
     * </pre>
     *
     * <code>string officeId = 6;</code>
     * @param value The officeId to set.
     * @return This builder for chaining.
     */
    public Builder setOfficeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      officeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 事業所ID
     * </pre>
     *
     * <code>string officeId = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOfficeId() {
      
      officeId_ = getDefaultInstance().getOfficeId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 事業所ID
     * </pre>
     *
     * <code>string officeId = 6;</code>
     * @param value The bytes for officeId to set.
     * @return This builder for chaining.
     */
    public Builder setOfficeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      officeId_ = value;
      onChanged();
      return this;
    }

    private int beaconType_ = 0;
    /**
     * <pre>
     *&#47; ビーコン導入種別
     * </pre>
     *
     * <code>.registration.REBeaconType beaconType = 7;</code>
     * @return The enum numeric value on the wire for beaconType.
     */
    @java.lang.Override public int getBeaconTypeValue() {
      return beaconType_;
    }
    /**
     * <pre>
     *&#47; ビーコン導入種別
     * </pre>
     *
     * <code>.registration.REBeaconType beaconType = 7;</code>
     * @param value The enum numeric value on the wire for beaconType to set.
     * @return This builder for chaining.
     */
    public Builder setBeaconTypeValue(int value) {
      
      beaconType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ビーコン導入種別
     * </pre>
     *
     * <code>.registration.REBeaconType beaconType = 7;</code>
     * @return The beaconType.
     */
    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REBeaconType getBeaconType() {
      @SuppressWarnings("deprecation")
      dr.app.core.autogen.grpc.registration.REBeaconType result = dr.app.core.autogen.grpc.registration.REBeaconType.valueOf(beaconType_);
      return result == null ? dr.app.core.autogen.grpc.registration.REBeaconType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *&#47; ビーコン導入種別
     * </pre>
     *
     * <code>.registration.REBeaconType beaconType = 7;</code>
     * @param value The beaconType to set.
     * @return This builder for chaining.
     */
    public Builder setBeaconType(dr.app.core.autogen.grpc.registration.REBeaconType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      beaconType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ビーコン導入種別
     * </pre>
     *
     * <code>.registration.REBeaconType beaconType = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearBeaconType() {
      
      beaconType_ = 0;
      onChanged();
      return this;
    }

    private boolean deleted_ ;
    /**
     * <pre>
     *&#47; 削除済フラグ
     * </pre>
     *
     * <code>bool deleted = 8;</code>
     * @return The deleted.
     */
    @java.lang.Override
    public boolean getDeleted() {
      return deleted_;
    }
    /**
     * <pre>
     *&#47; 削除済フラグ
     * </pre>
     *
     * <code>bool deleted = 8;</code>
     * @param value The deleted to set.
     * @return This builder for chaining.
     */
    public Builder setDeleted(boolean value) {
      
      deleted_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 削除済フラグ
     * </pre>
     *
     * <code>bool deleted = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeleted() {
      
      deleted_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:registration.REBeaconAttendanceArea)
  }

  // @@protoc_insertion_point(class_scope:registration.REBeaconAttendanceArea)
  private static final dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea();
  }

  public static dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<REBeaconAttendanceArea>
      PARSER = new com.google.protobuf.AbstractParser<REBeaconAttendanceArea>() {
    @java.lang.Override
    public REBeaconAttendanceArea parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new REBeaconAttendanceArea(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<REBeaconAttendanceArea> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<REBeaconAttendanceArea> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

