// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration.proto

package dr.app.core.autogen.grpc.registration;

public interface REBeaconAttendanceAreaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registration.REBeaconAttendanceArea)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *&#47; ビーコン勤怠エリアコレクションのオブジェクトID
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   *&#47; ビーコン勤怠エリアコレクションのオブジェクトID
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   *&#47; エリア名
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *&#47; エリア名
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *&#47; デフォルトの滞在理由
   * </pre>
   *
   * <code>.registration.REDefaultStayReason defaultStayReason = 3;</code>
   * @return The enum numeric value on the wire for defaultStayReason.
   */
  int getDefaultStayReasonValue();
  /**
   * <pre>
   *&#47; デフォルトの滞在理由
   * </pre>
   *
   * <code>.registration.REDefaultStayReason defaultStayReason = 3;</code>
   * @return The defaultStayReason.
   */
  dr.app.core.autogen.grpc.registration.REDefaultStayReason getDefaultStayReason();

  /**
   * <pre>
   *&#47; 表示色
   * </pre>
   *
   * <code>int32 color = 4;</code>
   * @return The color.
   */
  int getColor();

  /**
   * <pre>
   *&#47; エリアに紐づいたビーコンの数
   * </pre>
   *
   * <code>int64 linkedBeaconCount = 5;</code>
   * @return The linkedBeaconCount.
   */
  long getLinkedBeaconCount();

  /**
   * <pre>
   *&#47; 事業所ID
   * </pre>
   *
   * <code>string officeId = 6;</code>
   * @return The officeId.
   */
  java.lang.String getOfficeId();
  /**
   * <pre>
   *&#47; 事業所ID
   * </pre>
   *
   * <code>string officeId = 6;</code>
   * @return The bytes for officeId.
   */
  com.google.protobuf.ByteString
      getOfficeIdBytes();

  /**
   * <pre>
   *&#47; ビーコン導入種別
   * </pre>
   *
   * <code>.registration.REBeaconType beaconType = 7;</code>
   * @return The enum numeric value on the wire for beaconType.
   */
  int getBeaconTypeValue();
  /**
   * <pre>
   *&#47; ビーコン導入種別
   * </pre>
   *
   * <code>.registration.REBeaconType beaconType = 7;</code>
   * @return The beaconType.
   */
  dr.app.core.autogen.grpc.registration.REBeaconType getBeaconType();

  /**
   * <pre>
   *&#47; 削除済フラグ
   * </pre>
   *
   * <code>bool deleted = 8;</code>
   * @return The deleted.
   */
  boolean getDeleted();
}
