// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration.proto

package dr.app.core.autogen.grpc.registration;

/**
 * Protobuf enum {@code registration.REDefaultStayReason}
 */
public enum REDefaultStayReason
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *&#47; 業務
   * </pre>
   *
   * <code>WORK = 0;</code>
   */
  WORK(0),
  /**
   * <pre>
   *&#47; 自己研鑽
   * </pre>
   *
   * <code>RESEARCH = 1;</code>
   */
  RESEARCH(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *&#47; 業務
   * </pre>
   *
   * <code>WORK = 0;</code>
   */
  public static final int WORK_VALUE = 0;
  /**
   * <pre>
   *&#47; 自己研鑽
   * </pre>
   *
   * <code>RESEARCH = 1;</code>
   */
  public static final int RESEARCH_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static REDefaultStayReason valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static REDefaultStayReason forNumber(int value) {
    switch (value) {
      case 0: return WORK;
      case 1: return RESEARCH;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<REDefaultStayReason>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      REDefaultStayReason> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<REDefaultStayReason>() {
          public REDefaultStayReason findValueByNumber(int number) {
            return REDefaultStayReason.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final REDefaultStayReason[] VALUES = values();

  public static REDefaultStayReason valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private REDefaultStayReason(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:registration.REDefaultStayReason)
}

