// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration_auth.proto

package dr.app.core.autogen.grpc.registration;

public interface REGetLoginUserInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registration.REGetLoginUserInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.registration.REUserInfo userInfo = 1;</code>
   * @return Whether the userInfo field is set.
   */
  boolean hasUserInfo();
  /**
   * <code>.registration.REUserInfo userInfo = 1;</code>
   * @return The userInfo.
   */
  dr.app.core.autogen.grpc.registration.REUserInfo getUserInfo();
  /**
   * <code>.registration.REUserInfo userInfo = 1;</code>
   */
  dr.app.core.autogen.grpc.registration.REUserInfoOrBuilder getUserInfoOrBuilder();

  /**
   * <code>.registration.REOfficeInfo officeInfo = 2;</code>
   * @return Whether the officeInfo field is set.
   */
  boolean hasOfficeInfo();
  /**
   * <code>.registration.REOfficeInfo officeInfo = 2;</code>
   * @return The officeInfo.
   */
  dr.app.core.autogen.grpc.registration.REOfficeInfo getOfficeInfo();
  /**
   * <code>.registration.REOfficeInfo officeInfo = 2;</code>
   */
  dr.app.core.autogen.grpc.registration.REOfficeInfoOrBuilder getOfficeInfoOrBuilder();
}
