// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration_auth.proto

package dr.app.core.autogen.grpc.registration;

public interface REGetLoginUserInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registration.REGetLoginUserInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *&#47; 事業所ユーザID
   * </pre>
   *
   * <code>string officeUserId = 1;</code>
   * @return The officeUserId.
   */
  java.lang.String getOfficeUserId();
  /**
   * <pre>
   *&#47; 事業所ユーザID
   * </pre>
   *
   * <code>string officeUserId = 1;</code>
   * @return The bytes for officeUserId.
   */
  com.google.protobuf.ByteString
      getOfficeUserIdBytes();
}
