// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration_auth.proto

package dr.app.core.autogen.grpc.registration;

/**
 * Protobuf type {@code registration.REGetLoginUserInfoResponse}
 */
public final class REGetLoginUserInfoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:registration.REGetLoginUserInfoResponse)
    REGetLoginUserInfoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use REGetLoginUserInfoResponse.newBuilder() to construct.
  private REGetLoginUserInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private REGetLoginUserInfoResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new REGetLoginUserInfoResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private REGetLoginUserInfoResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            dr.app.core.autogen.grpc.registration.REUserInfo.Builder subBuilder = null;
            if (userInfo_ != null) {
              subBuilder = userInfo_.toBuilder();
            }
            userInfo_ = input.readMessage(dr.app.core.autogen.grpc.registration.REUserInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userInfo_);
              userInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            dr.app.core.autogen.grpc.registration.REOfficeInfo.Builder subBuilder = null;
            if (officeInfo_ != null) {
              subBuilder = officeInfo_.toBuilder();
            }
            officeInfo_ = input.readMessage(dr.app.core.autogen.grpc.registration.REOfficeInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(officeInfo_);
              officeInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dr.app.core.autogen.grpc.registration.RegistrationAuthOuterClass.internal_static_registration_REGetLoginUserInfoResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dr.app.core.autogen.grpc.registration.RegistrationAuthOuterClass.internal_static_registration_REGetLoginUserInfoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse.class, dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse.Builder.class);
  }

  public static final int USERINFO_FIELD_NUMBER = 1;
  private dr.app.core.autogen.grpc.registration.REUserInfo userInfo_;
  /**
   * <code>.registration.REUserInfo userInfo = 1;</code>
   * @return Whether the userInfo field is set.
   */
  @java.lang.Override
  public boolean hasUserInfo() {
    return userInfo_ != null;
  }
  /**
   * <code>.registration.REUserInfo userInfo = 1;</code>
   * @return The userInfo.
   */
  @java.lang.Override
  public dr.app.core.autogen.grpc.registration.REUserInfo getUserInfo() {
    return userInfo_ == null ? dr.app.core.autogen.grpc.registration.REUserInfo.getDefaultInstance() : userInfo_;
  }
  /**
   * <code>.registration.REUserInfo userInfo = 1;</code>
   */
  @java.lang.Override
  public dr.app.core.autogen.grpc.registration.REUserInfoOrBuilder getUserInfoOrBuilder() {
    return getUserInfo();
  }

  public static final int OFFICEINFO_FIELD_NUMBER = 2;
  private dr.app.core.autogen.grpc.registration.REOfficeInfo officeInfo_;
  /**
   * <code>.registration.REOfficeInfo officeInfo = 2;</code>
   * @return Whether the officeInfo field is set.
   */
  @java.lang.Override
  public boolean hasOfficeInfo() {
    return officeInfo_ != null;
  }
  /**
   * <code>.registration.REOfficeInfo officeInfo = 2;</code>
   * @return The officeInfo.
   */
  @java.lang.Override
  public dr.app.core.autogen.grpc.registration.REOfficeInfo getOfficeInfo() {
    return officeInfo_ == null ? dr.app.core.autogen.grpc.registration.REOfficeInfo.getDefaultInstance() : officeInfo_;
  }
  /**
   * <code>.registration.REOfficeInfo officeInfo = 2;</code>
   */
  @java.lang.Override
  public dr.app.core.autogen.grpc.registration.REOfficeInfoOrBuilder getOfficeInfoOrBuilder() {
    return getOfficeInfo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userInfo_ != null) {
      output.writeMessage(1, getUserInfo());
    }
    if (officeInfo_ != null) {
      output.writeMessage(2, getOfficeInfo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUserInfo());
    }
    if (officeInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOfficeInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse)) {
      return super.equals(obj);
    }
    dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse other = (dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse) obj;

    if (hasUserInfo() != other.hasUserInfo()) return false;
    if (hasUserInfo()) {
      if (!getUserInfo()
          .equals(other.getUserInfo())) return false;
    }
    if (hasOfficeInfo() != other.hasOfficeInfo()) return false;
    if (hasOfficeInfo()) {
      if (!getOfficeInfo()
          .equals(other.getOfficeInfo())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUserInfo()) {
      hash = (37 * hash) + USERINFO_FIELD_NUMBER;
      hash = (53 * hash) + getUserInfo().hashCode();
    }
    if (hasOfficeInfo()) {
      hash = (37 * hash) + OFFICEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getOfficeInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code registration.REGetLoginUserInfoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:registration.REGetLoginUserInfoResponse)
      dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dr.app.core.autogen.grpc.registration.RegistrationAuthOuterClass.internal_static_registration_REGetLoginUserInfoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dr.app.core.autogen.grpc.registration.RegistrationAuthOuterClass.internal_static_registration_REGetLoginUserInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse.class, dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse.Builder.class);
    }

    // Construct using dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userInfoBuilder_ == null) {
        userInfo_ = null;
      } else {
        userInfo_ = null;
        userInfoBuilder_ = null;
      }
      if (officeInfoBuilder_ == null) {
        officeInfo_ = null;
      } else {
        officeInfo_ = null;
        officeInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dr.app.core.autogen.grpc.registration.RegistrationAuthOuterClass.internal_static_registration_REGetLoginUserInfoResponse_descriptor;
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse getDefaultInstanceForType() {
      return dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse.getDefaultInstance();
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse build() {
      dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse buildPartial() {
      dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse result = new dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse(this);
      if (userInfoBuilder_ == null) {
        result.userInfo_ = userInfo_;
      } else {
        result.userInfo_ = userInfoBuilder_.build();
      }
      if (officeInfoBuilder_ == null) {
        result.officeInfo_ = officeInfo_;
      } else {
        result.officeInfo_ = officeInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse) {
        return mergeFrom((dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse other) {
      if (other == dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse.getDefaultInstance()) return this;
      if (other.hasUserInfo()) {
        mergeUserInfo(other.getUserInfo());
      }
      if (other.hasOfficeInfo()) {
        mergeOfficeInfo(other.getOfficeInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private dr.app.core.autogen.grpc.registration.REUserInfo userInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dr.app.core.autogen.grpc.registration.REUserInfo, dr.app.core.autogen.grpc.registration.REUserInfo.Builder, dr.app.core.autogen.grpc.registration.REUserInfoOrBuilder> userInfoBuilder_;
    /**
     * <code>.registration.REUserInfo userInfo = 1;</code>
     * @return Whether the userInfo field is set.
     */
    public boolean hasUserInfo() {
      return userInfoBuilder_ != null || userInfo_ != null;
    }
    /**
     * <code>.registration.REUserInfo userInfo = 1;</code>
     * @return The userInfo.
     */
    public dr.app.core.autogen.grpc.registration.REUserInfo getUserInfo() {
      if (userInfoBuilder_ == null) {
        return userInfo_ == null ? dr.app.core.autogen.grpc.registration.REUserInfo.getDefaultInstance() : userInfo_;
      } else {
        return userInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.registration.REUserInfo userInfo = 1;</code>
     */
    public Builder setUserInfo(dr.app.core.autogen.grpc.registration.REUserInfo value) {
      if (userInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userInfo_ = value;
        onChanged();
      } else {
        userInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.registration.REUserInfo userInfo = 1;</code>
     */
    public Builder setUserInfo(
        dr.app.core.autogen.grpc.registration.REUserInfo.Builder builderForValue) {
      if (userInfoBuilder_ == null) {
        userInfo_ = builderForValue.build();
        onChanged();
      } else {
        userInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.registration.REUserInfo userInfo = 1;</code>
     */
    public Builder mergeUserInfo(dr.app.core.autogen.grpc.registration.REUserInfo value) {
      if (userInfoBuilder_ == null) {
        if (userInfo_ != null) {
          userInfo_ =
            dr.app.core.autogen.grpc.registration.REUserInfo.newBuilder(userInfo_).mergeFrom(value).buildPartial();
        } else {
          userInfo_ = value;
        }
        onChanged();
      } else {
        userInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.registration.REUserInfo userInfo = 1;</code>
     */
    public Builder clearUserInfo() {
      if (userInfoBuilder_ == null) {
        userInfo_ = null;
        onChanged();
      } else {
        userInfo_ = null;
        userInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.registration.REUserInfo userInfo = 1;</code>
     */
    public dr.app.core.autogen.grpc.registration.REUserInfo.Builder getUserInfoBuilder() {
      
      onChanged();
      return getUserInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.registration.REUserInfo userInfo = 1;</code>
     */
    public dr.app.core.autogen.grpc.registration.REUserInfoOrBuilder getUserInfoOrBuilder() {
      if (userInfoBuilder_ != null) {
        return userInfoBuilder_.getMessageOrBuilder();
      } else {
        return userInfo_ == null ?
            dr.app.core.autogen.grpc.registration.REUserInfo.getDefaultInstance() : userInfo_;
      }
    }
    /**
     * <code>.registration.REUserInfo userInfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dr.app.core.autogen.grpc.registration.REUserInfo, dr.app.core.autogen.grpc.registration.REUserInfo.Builder, dr.app.core.autogen.grpc.registration.REUserInfoOrBuilder> 
        getUserInfoFieldBuilder() {
      if (userInfoBuilder_ == null) {
        userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dr.app.core.autogen.grpc.registration.REUserInfo, dr.app.core.autogen.grpc.registration.REUserInfo.Builder, dr.app.core.autogen.grpc.registration.REUserInfoOrBuilder>(
                getUserInfo(),
                getParentForChildren(),
                isClean());
        userInfo_ = null;
      }
      return userInfoBuilder_;
    }

    private dr.app.core.autogen.grpc.registration.REOfficeInfo officeInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        dr.app.core.autogen.grpc.registration.REOfficeInfo, dr.app.core.autogen.grpc.registration.REOfficeInfo.Builder, dr.app.core.autogen.grpc.registration.REOfficeInfoOrBuilder> officeInfoBuilder_;
    /**
     * <code>.registration.REOfficeInfo officeInfo = 2;</code>
     * @return Whether the officeInfo field is set.
     */
    public boolean hasOfficeInfo() {
      return officeInfoBuilder_ != null || officeInfo_ != null;
    }
    /**
     * <code>.registration.REOfficeInfo officeInfo = 2;</code>
     * @return The officeInfo.
     */
    public dr.app.core.autogen.grpc.registration.REOfficeInfo getOfficeInfo() {
      if (officeInfoBuilder_ == null) {
        return officeInfo_ == null ? dr.app.core.autogen.grpc.registration.REOfficeInfo.getDefaultInstance() : officeInfo_;
      } else {
        return officeInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.registration.REOfficeInfo officeInfo = 2;</code>
     */
    public Builder setOfficeInfo(dr.app.core.autogen.grpc.registration.REOfficeInfo value) {
      if (officeInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        officeInfo_ = value;
        onChanged();
      } else {
        officeInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.registration.REOfficeInfo officeInfo = 2;</code>
     */
    public Builder setOfficeInfo(
        dr.app.core.autogen.grpc.registration.REOfficeInfo.Builder builderForValue) {
      if (officeInfoBuilder_ == null) {
        officeInfo_ = builderForValue.build();
        onChanged();
      } else {
        officeInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.registration.REOfficeInfo officeInfo = 2;</code>
     */
    public Builder mergeOfficeInfo(dr.app.core.autogen.grpc.registration.REOfficeInfo value) {
      if (officeInfoBuilder_ == null) {
        if (officeInfo_ != null) {
          officeInfo_ =
            dr.app.core.autogen.grpc.registration.REOfficeInfo.newBuilder(officeInfo_).mergeFrom(value).buildPartial();
        } else {
          officeInfo_ = value;
        }
        onChanged();
      } else {
        officeInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.registration.REOfficeInfo officeInfo = 2;</code>
     */
    public Builder clearOfficeInfo() {
      if (officeInfoBuilder_ == null) {
        officeInfo_ = null;
        onChanged();
      } else {
        officeInfo_ = null;
        officeInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.registration.REOfficeInfo officeInfo = 2;</code>
     */
    public dr.app.core.autogen.grpc.registration.REOfficeInfo.Builder getOfficeInfoBuilder() {
      
      onChanged();
      return getOfficeInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.registration.REOfficeInfo officeInfo = 2;</code>
     */
    public dr.app.core.autogen.grpc.registration.REOfficeInfoOrBuilder getOfficeInfoOrBuilder() {
      if (officeInfoBuilder_ != null) {
        return officeInfoBuilder_.getMessageOrBuilder();
      } else {
        return officeInfo_ == null ?
            dr.app.core.autogen.grpc.registration.REOfficeInfo.getDefaultInstance() : officeInfo_;
      }
    }
    /**
     * <code>.registration.REOfficeInfo officeInfo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        dr.app.core.autogen.grpc.registration.REOfficeInfo, dr.app.core.autogen.grpc.registration.REOfficeInfo.Builder, dr.app.core.autogen.grpc.registration.REOfficeInfoOrBuilder> 
        getOfficeInfoFieldBuilder() {
      if (officeInfoBuilder_ == null) {
        officeInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            dr.app.core.autogen.grpc.registration.REOfficeInfo, dr.app.core.autogen.grpc.registration.REOfficeInfo.Builder, dr.app.core.autogen.grpc.registration.REOfficeInfoOrBuilder>(
                getOfficeInfo(),
                getParentForChildren(),
                isClean());
        officeInfo_ = null;
      }
      return officeInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:registration.REGetLoginUserInfoResponse)
  }

  // @@protoc_insertion_point(class_scope:registration.REGetLoginUserInfoResponse)
  private static final dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse();
  }

  public static dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<REGetLoginUserInfoResponse>
      PARSER = new com.google.protobuf.AbstractParser<REGetLoginUserInfoResponse>() {
    @java.lang.Override
    public REGetLoginUserInfoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new REGetLoginUserInfoResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<REGetLoginUserInfoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<REGetLoginUserInfoResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dr.app.core.autogen.grpc.registration.REGetLoginUserInfoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

