// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration.proto

package dr.app.core.autogen.grpc.registration;

public final class RegistrationOuterClass {
  private RegistrationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registration_REListInstallationBeaconRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registration_REListInstallationBeaconRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registration_REListInstallationBeaconResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registration_REListInstallationBeaconResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registration_REInstallationBeacon_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registration_REInstallationBeacon_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registration_REInstallationBeacon_REAreaHistory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registration_REInstallationBeacon_REAreaHistory_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registration_REListBeaconAreaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registration_REListBeaconAreaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registration_REListBeaconAttendanceAreaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registration_REListBeaconAttendanceAreaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registration_REBeaconAttendanceArea_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registration_REBeaconAttendanceArea_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_registration_RERole_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_registration_RERole_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022registration.proto\022\014registration\032\033goog" +
      "le/protobuf/empty.proto\032\037google/protobuf" +
      "/timestamp.proto\032\014common.proto\032\014master.p" +
      "roto\"\340\002\n\037REListInstallationBeaconRequest" +
      "\022\017\n\007keyword\030\001 \001(\t\022\020\n\010officeId\030\002 \001(\t\022\016\n\006o" +
      "ffset\030\003 \001(\005\022\r\n\005limit\030\004 \001(\005\022]\n\033linkStatus" +
      "ForAttendanceArea\030\005 \001(\01628.registration.R" +
      "EListInstallationBeaconRequest.LinkStatu" +
      "s\022_\n\035linkStatusForMrManagementArea\030\006 \001(\016" +
      "28.registration.REListInstallationBeacon" +
      "Request.LinkStatus\";\n\nLinkStatus\022\017\n\013ONLY" +
      "_LINKED\020\000\022\023\n\017ONLY_NOT_LINKED\020\001\022\007\n\003ALL\020\002\"" +
      "u\n REListInstallationBeaconResponse\022\020\n\010a" +
      "llCount\030\001 \001(\003\022?\n\023installationBeacons\030\002 \003" +
      "(\0132\".registration.REInstallationBeacon\"\242" +
      "\004\n\024REInstallationBeacon\022\034\n\024installationB" +
      "eaconId\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\020\n\010officeId\030" +
      "\003 \001(\t\022\013\n\003mac\030\004 \001(\t\022\014\n\004uuid\030\005 \001(\t\022\r\n\005majo" +
      "r\030\006 \001(\005\022\r\n\005minor\030\007 \001(\005\022\014\n\004note\030\010 \001(\t\022\024\n\014" +
      "isMqttDevice\030\t \001(\010\022$\n\034linkedBeaconAttend" +
      "anceAreaId\030\n \001(\t\022&\n\036linkedBeaconMrManage" +
      "mentAreaId\030\013 \001(\t\022W\n\035beaconAttendanceArea" +
      "Histories\030\014 \003(\01320.registration.REInstall" +
      "ationBeacon.REAreaHistory\022Y\n\037beaconMrMan" +
      "agementAreaHistories\030\r \003(\01320.registratio" +
      "n.REInstallationBeacon.REAreaHistory\022\017\n\007" +
      "deleted\030\016 \001(\010\022\017\n\007updated\030\017 \001(\003\032K\n\rREArea" +
      "History\022\016\n\006areaId\030\001 \001(\t\022\020\n\010areaName\030\002 \001(" +
      "\t\022\014\n\004from\030\003 \001(\003\022\n\n\002to\030\004 \001(\003\"[\n\027REListBea" +
      "conAreaRequest\022\017\n\007keyword\030\001 \001(\t\022\020\n\010offic" +
      "eId\030\002 \001(\t\022\016\n\006offset\030\003 \001(\005\022\r\n\005limit\030\004 \001(\005" +
      "\"\230\001\n\"REListBeaconAttendanceAreaResponse\022" +
      "\020\n\010allCount\030\001 \001(\003\022B\n\024beaconAttendanceAre" +
      "a\030\002 \003(\0132$.registration.REBeaconAttendanc" +
      "eArea\022\034\n\024notLinkedBeaconCount\030\003 \001(\005\"\355\001\n\026" +
      "REBeaconAttendanceArea\022\n\n\002id\030\001 \001(\t\022\014\n\004na" +
      "me\030\002 \001(\t\022<\n\021defaultStayReason\030\003 \001(\0162!.re" +
      "gistration.REDefaultStayReason\022\r\n\005color\030" +
      "\004 \001(\005\022\031\n\021linkedBeaconCount\030\005 \001(\003\022\020\n\010offi" +
      "ceId\030\006 \001(\t\022.\n\nbeaconType\030\007 \001(\0162\032.registr" +
      "ation.REBeaconType\022\017\n\007deleted\030\010 \001(\010\"\336\001\n\006" +
      "RERole\022\n\n\002id\030\001 \001(\t\022\014\n\004code\030\002 \001(\t\022\014\n\004name" +
      "\030\003 \001(\t\022\024\n\014displayOrder\030\004 \001(\005\022\r\n\005added\030\005 " +
      "\001(\t\022\017\n\007deleted\030\006 \001(\t\022\024\n\014functionCode\030\007 \001" +
      "(\t\022\034\n\024functionDisplayOrder\030\010 \001(\005\022\017\n\007crea" +
      "ted\030\t \001(\t\022\017\n\007creator\030\n \001(\t\022\017\n\007updated\030\013 " +
      "\001(\t\022\017\n\007updater\030\014 \001(\t*-\n\023REDefaultStayRea" +
      "son\022\010\n\004WORK\020\000\022\014\n\010RESEARCH\020\001*&\n\014REBeaconT" +
      "ype\022\t\n\005DRJOY\020\000\022\013\n\007BEACAPP\020\001*D\n\014REOfficeT" +
      "ype\022\013\n\007MEDICAL\020\000\022\014\n\010PHARMACY\020\001\022\016\n\nDRUG_S" +
      "TORE\020\002\022\t\n\005OTHER\020\003*5\n\025REManagementAuthori" +
      "ty\022\010\n\004MP_1\020\000\022\010\n\004MP_2\020\001\022\010\n\004MP_3\020\0022\374\001\n\014Reg" +
      "istration\022w\n\026listInstallationBeacon\022-.re" +
      "gistration.REListInstallationBeaconReque" +
      "st\032..registration.REListInstallationBeac" +
      "onResponse\022s\n\030listBeaconAttendanceArea\022%" +
      ".registration.REListBeaconAreaRequest\0320." +
      "registration.REListBeaconAttendanceAreaR" +
      "esponseB)\n%dr.app.core.autogen.grpc.regi" +
      "strationP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          dr.app.core.autogen.grpc.common.Common.getDescriptor(),
          dr.app.core.autogen.grpc.master.Master.getDescriptor(),
        });
    internal_static_registration_REListInstallationBeaconRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_registration_REListInstallationBeaconRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registration_REListInstallationBeaconRequest_descriptor,
        new java.lang.String[] { "Keyword", "OfficeId", "Offset", "Limit", "LinkStatusForAttendanceArea", "LinkStatusForMrManagementArea", });
    internal_static_registration_REListInstallationBeaconResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_registration_REListInstallationBeaconResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registration_REListInstallationBeaconResponse_descriptor,
        new java.lang.String[] { "AllCount", "InstallationBeacons", });
    internal_static_registration_REInstallationBeacon_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_registration_REInstallationBeacon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registration_REInstallationBeacon_descriptor,
        new java.lang.String[] { "InstallationBeaconId", "Name", "OfficeId", "Mac", "Uuid", "Major", "Minor", "Note", "IsMqttDevice", "LinkedBeaconAttendanceAreaId", "LinkedBeaconMrManagementAreaId", "BeaconAttendanceAreaHistories", "BeaconMrManagementAreaHistories", "Deleted", "Updated", });
    internal_static_registration_REInstallationBeacon_REAreaHistory_descriptor =
      internal_static_registration_REInstallationBeacon_descriptor.getNestedTypes().get(0);
    internal_static_registration_REInstallationBeacon_REAreaHistory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registration_REInstallationBeacon_REAreaHistory_descriptor,
        new java.lang.String[] { "AreaId", "AreaName", "From", "To", });
    internal_static_registration_REListBeaconAreaRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_registration_REListBeaconAreaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registration_REListBeaconAreaRequest_descriptor,
        new java.lang.String[] { "Keyword", "OfficeId", "Offset", "Limit", });
    internal_static_registration_REListBeaconAttendanceAreaResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_registration_REListBeaconAttendanceAreaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registration_REListBeaconAttendanceAreaResponse_descriptor,
        new java.lang.String[] { "AllCount", "BeaconAttendanceArea", "NotLinkedBeaconCount", });
    internal_static_registration_REBeaconAttendanceArea_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_registration_REBeaconAttendanceArea_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registration_REBeaconAttendanceArea_descriptor,
        new java.lang.String[] { "Id", "Name", "DefaultStayReason", "Color", "LinkedBeaconCount", "OfficeId", "BeaconType", "Deleted", });
    internal_static_registration_RERole_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_registration_RERole_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_registration_RERole_descriptor,
        new java.lang.String[] { "Id", "Code", "Name", "DisplayOrder", "Added", "Deleted", "FunctionCode", "FunctionDisplayOrder", "Created", "Creator", "Updated", "Updater", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    dr.app.core.autogen.grpc.common.Common.getDescriptor();
    dr.app.core.autogen.grpc.master.Master.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
