// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration.proto

package dr.app.core.autogen.grpc.registration;

public interface REInstallationBeaconOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registration.REInstallationBeacon)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *&#47; installation_beaconsのオブジェクトID
   * </pre>
   *
   * <code>string installationBeaconId = 1;</code>
   * @return The installationBeaconId.
   */
  java.lang.String getInstallationBeaconId();
  /**
   * <pre>
   *&#47; installation_beaconsのオブジェクトID
   * </pre>
   *
   * <code>string installationBeaconId = 1;</code>
   * @return The bytes for installationBeaconId.
   */
  com.google.protobuf.ByteString
      getInstallationBeaconIdBytes();

  /**
   * <pre>
   *&#47; ビーコン名
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *&#47; ビーコン名
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *&#47; 事業所ID
   * </pre>
   *
   * <code>string officeId = 3;</code>
   * @return The officeId.
   */
  java.lang.String getOfficeId();
  /**
   * <pre>
   *&#47; 事業所ID
   * </pre>
   *
   * <code>string officeId = 3;</code>
   * @return The bytes for officeId.
   */
  com.google.protobuf.ByteString
      getOfficeIdBytes();

  /**
   * <pre>
   *&#47; MACアドレス
   * </pre>
   *
   * <code>string mac = 4;</code>
   * @return The mac.
   */
  java.lang.String getMac();
  /**
   * <pre>
   *&#47; MACアドレス
   * </pre>
   *
   * <code>string mac = 4;</code>
   * @return The bytes for mac.
   */
  com.google.protobuf.ByteString
      getMacBytes();

  /**
   * <pre>
   *&#47; iBeaconにおけるUUID
   * </pre>
   *
   * <code>string uuid = 5;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <pre>
   *&#47; iBeaconにおけるUUID
   * </pre>
   *
   * <code>string uuid = 5;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <pre>
   *&#47; iBeaconにおけるMajor値
   * </pre>
   *
   * <code>int32 major = 6;</code>
   * @return The major.
   */
  int getMajor();

  /**
   * <pre>
   *&#47; iBeaconにおけるMinor値
   * </pre>
   *
   * <code>int32 minor = 7;</code>
   * @return The minor.
   */
  int getMinor();

  /**
   * <pre>
   *&#47; 備考
   * </pre>
   *
   * <code>string note = 8;</code>
   * @return The note.
   */
  java.lang.String getNote();
  /**
   * <pre>
   *&#47; 備考
   * </pre>
   *
   * <code>string note = 8;</code>
   * @return The bytes for note.
   */
  com.google.protobuf.ByteString
      getNoteBytes();

  /**
   * <pre>
   *&#47; MQTTデバイスとして登録するかどうかのフラグ
   * </pre>
   *
   * <code>bool isMqttDevice = 9;</code>
   * @return The isMqttDevice.
   */
  boolean getIsMqttDevice();

  /**
   * <pre>
   *&#47; リンクされているビーコン勤怠エリアのオブジェクトID
   * </pre>
   *
   * <code>string linkedBeaconAttendanceAreaId = 10;</code>
   * @return The linkedBeaconAttendanceAreaId.
   */
  java.lang.String getLinkedBeaconAttendanceAreaId();
  /**
   * <pre>
   *&#47; リンクされているビーコン勤怠エリアのオブジェクトID
   * </pre>
   *
   * <code>string linkedBeaconAttendanceAreaId = 10;</code>
   * @return The bytes for linkedBeaconAttendanceAreaId.
   */
  com.google.protobuf.ByteString
      getLinkedBeaconAttendanceAreaIdBytes();

  /**
   * <pre>
   *&#47; リンクされているビーコンMr管理エリアのオブジェクトID
   * </pre>
   *
   * <code>string linkedBeaconMrManagementAreaId = 11;</code>
   * @return The linkedBeaconMrManagementAreaId.
   */
  java.lang.String getLinkedBeaconMrManagementAreaId();
  /**
   * <pre>
   *&#47; リンクされているビーコンMr管理エリアのオブジェクトID
   * </pre>
   *
   * <code>string linkedBeaconMrManagementAreaId = 11;</code>
   * @return The bytes for linkedBeaconMrManagementAreaId.
   */
  com.google.protobuf.ByteString
      getLinkedBeaconMrManagementAreaIdBytes();

  /**
   * <pre>
   *&#47; ビーコン勤怠エリア紐付け履歴
   * </pre>
   *
   * <code>repeated .registration.REInstallationBeacon.REAreaHistory beaconAttendanceAreaHistories = 12;</code>
   */
  java.util.List<dr.app.core.autogen.grpc.registration.REInstallationBeacon.REAreaHistory> 
      getBeaconAttendanceAreaHistoriesList();
  /**
   * <pre>
   *&#47; ビーコン勤怠エリア紐付け履歴
   * </pre>
   *
   * <code>repeated .registration.REInstallationBeacon.REAreaHistory beaconAttendanceAreaHistories = 12;</code>
   */
  dr.app.core.autogen.grpc.registration.REInstallationBeacon.REAreaHistory getBeaconAttendanceAreaHistories(int index);
  /**
   * <pre>
   *&#47; ビーコン勤怠エリア紐付け履歴
   * </pre>
   *
   * <code>repeated .registration.REInstallationBeacon.REAreaHistory beaconAttendanceAreaHistories = 12;</code>
   */
  int getBeaconAttendanceAreaHistoriesCount();
  /**
   * <pre>
   *&#47; ビーコン勤怠エリア紐付け履歴
   * </pre>
   *
   * <code>repeated .registration.REInstallationBeacon.REAreaHistory beaconAttendanceAreaHistories = 12;</code>
   */
  java.util.List<? extends dr.app.core.autogen.grpc.registration.REInstallationBeacon.REAreaHistoryOrBuilder> 
      getBeaconAttendanceAreaHistoriesOrBuilderList();
  /**
   * <pre>
   *&#47; ビーコン勤怠エリア紐付け履歴
   * </pre>
   *
   * <code>repeated .registration.REInstallationBeacon.REAreaHistory beaconAttendanceAreaHistories = 12;</code>
   */
  dr.app.core.autogen.grpc.registration.REInstallationBeacon.REAreaHistoryOrBuilder getBeaconAttendanceAreaHistoriesOrBuilder(
      int index);

  /**
   * <pre>
   *&#47; ビーコンMr管理エリア紐付け履歴
   * </pre>
   *
   * <code>repeated .registration.REInstallationBeacon.REAreaHistory beaconMrManagementAreaHistories = 13;</code>
   */
  java.util.List<dr.app.core.autogen.grpc.registration.REInstallationBeacon.REAreaHistory> 
      getBeaconMrManagementAreaHistoriesList();
  /**
   * <pre>
   *&#47; ビーコンMr管理エリア紐付け履歴
   * </pre>
   *
   * <code>repeated .registration.REInstallationBeacon.REAreaHistory beaconMrManagementAreaHistories = 13;</code>
   */
  dr.app.core.autogen.grpc.registration.REInstallationBeacon.REAreaHistory getBeaconMrManagementAreaHistories(int index);
  /**
   * <pre>
   *&#47; ビーコンMr管理エリア紐付け履歴
   * </pre>
   *
   * <code>repeated .registration.REInstallationBeacon.REAreaHistory beaconMrManagementAreaHistories = 13;</code>
   */
  int getBeaconMrManagementAreaHistoriesCount();
  /**
   * <pre>
   *&#47; ビーコンMr管理エリア紐付け履歴
   * </pre>
   *
   * <code>repeated .registration.REInstallationBeacon.REAreaHistory beaconMrManagementAreaHistories = 13;</code>
   */
  java.util.List<? extends dr.app.core.autogen.grpc.registration.REInstallationBeacon.REAreaHistoryOrBuilder> 
      getBeaconMrManagementAreaHistoriesOrBuilderList();
  /**
   * <pre>
   *&#47; ビーコンMr管理エリア紐付け履歴
   * </pre>
   *
   * <code>repeated .registration.REInstallationBeacon.REAreaHistory beaconMrManagementAreaHistories = 13;</code>
   */
  dr.app.core.autogen.grpc.registration.REInstallationBeacon.REAreaHistoryOrBuilder getBeaconMrManagementAreaHistoriesOrBuilder(
      int index);

  /**
   * <pre>
   *&#47; 削除済フラグ
   * </pre>
   *
   * <code>bool deleted = 14;</code>
   * @return The deleted.
   */
  boolean getDeleted();

  /**
   * <pre>
   *&#47; 最終更新時間
   * </pre>
   *
   * <code>int64 updated = 15;</code>
   * @return The updated.
   */
  long getUpdated();
}
