// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration.proto

package dr.app.core.autogen.grpc.registration;

/**
 * Protobuf type {@code registration.REListInstallationBeaconRequest}
 */
public final class REListInstallationBeaconRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:registration.REListInstallationBeaconRequest)
    REListInstallationBeaconRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use REListInstallationBeaconRequest.newBuilder() to construct.
  private REListInstallationBeaconRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private REListInstallationBeaconRequest() {
    keyword_ = "";
    officeId_ = "";
    linkStatusForAttendanceArea_ = 0;
    linkStatusForMrManagementArea_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new REListInstallationBeaconRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private REListInstallationBeaconRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            keyword_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            officeId_ = s;
            break;
          }
          case 24: {

            offset_ = input.readInt32();
            break;
          }
          case 32: {

            limit_ = input.readInt32();
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            linkStatusForAttendanceArea_ = rawValue;
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            linkStatusForMrManagementArea_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.internal_static_registration_REListInstallationBeaconRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.internal_static_registration_REListInstallationBeaconRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.class, dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code registration.REListInstallationBeaconRequest.LinkStatus}
   */
  public enum LinkStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * リンクされたもののみ
     * </pre>
     *
     * <code>ONLY_LINKED = 0;</code>
     */
    ONLY_LINKED(0),
    /**
     * <pre>
     * リンクされていないもののみ
     * </pre>
     *
     * <code>ONLY_NOT_LINKED = 1;</code>
     */
    ONLY_NOT_LINKED(1),
    /**
     * <pre>
     * 全て
     * </pre>
     *
     * <code>ALL = 2;</code>
     */
    ALL(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * リンクされたもののみ
     * </pre>
     *
     * <code>ONLY_LINKED = 0;</code>
     */
    public static final int ONLY_LINKED_VALUE = 0;
    /**
     * <pre>
     * リンクされていないもののみ
     * </pre>
     *
     * <code>ONLY_NOT_LINKED = 1;</code>
     */
    public static final int ONLY_NOT_LINKED_VALUE = 1;
    /**
     * <pre>
     * 全て
     * </pre>
     *
     * <code>ALL = 2;</code>
     */
    public static final int ALL_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LinkStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static LinkStatus forNumber(int value) {
      switch (value) {
        case 0: return ONLY_LINKED;
        case 1: return ONLY_NOT_LINKED;
        case 2: return ALL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LinkStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LinkStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LinkStatus>() {
            public LinkStatus findValueByNumber(int number) {
              return LinkStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final LinkStatus[] VALUES = values();

    public static LinkStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LinkStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:registration.REListInstallationBeaconRequest.LinkStatus)
  }

  public static final int KEYWORD_FIELD_NUMBER = 1;
  private volatile java.lang.Object keyword_;
  /**
   * <pre>
   *&#47; 検索キーワード
   * </pre>
   *
   * <code>string keyword = 1;</code>
   * @return The keyword.
   */
  @java.lang.Override
  public java.lang.String getKeyword() {
    java.lang.Object ref = keyword_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      keyword_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; 検索キーワード
   * </pre>
   *
   * <code>string keyword = 1;</code>
   * @return The bytes for keyword.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeywordBytes() {
    java.lang.Object ref = keyword_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      keyword_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OFFICEID_FIELD_NUMBER = 2;
  private volatile java.lang.Object officeId_;
  /**
   * <pre>
   *&#47; 事業所ID
   * </pre>
   *
   * <code>string officeId = 2;</code>
   * @return The officeId.
   */
  @java.lang.Override
  public java.lang.String getOfficeId() {
    java.lang.Object ref = officeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      officeId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; 事業所ID
   * </pre>
   *
   * <code>string officeId = 2;</code>
   * @return The bytes for officeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOfficeIdBytes() {
    java.lang.Object ref = officeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      officeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OFFSET_FIELD_NUMBER = 3;
  private int offset_;
  /**
   * <pre>
   *&#47; オフセット
   * </pre>
   *
   * <code>int32 offset = 3;</code>
   * @return The offset.
   */
  @java.lang.Override
  public int getOffset() {
    return offset_;
  }

  public static final int LIMIT_FIELD_NUMBER = 4;
  private int limit_;
  /**
   * <pre>
   *&#47; 最大取得件数
   * </pre>
   *
   * <code>int32 limit = 4;</code>
   * @return The limit.
   */
  @java.lang.Override
  public int getLimit() {
    return limit_;
  }

  public static final int LINKSTATUSFORATTENDANCEAREA_FIELD_NUMBER = 5;
  private int linkStatusForAttendanceArea_;
  /**
   * <pre>
   *&#47; ビーコン勤怠エリアとのリンク状態
   * </pre>
   *
   * <code>.registration.REListInstallationBeaconRequest.LinkStatus linkStatusForAttendanceArea = 5;</code>
   * @return The enum numeric value on the wire for linkStatusForAttendanceArea.
   */
  @java.lang.Override public int getLinkStatusForAttendanceAreaValue() {
    return linkStatusForAttendanceArea_;
  }
  /**
   * <pre>
   *&#47; ビーコン勤怠エリアとのリンク状態
   * </pre>
   *
   * <code>.registration.REListInstallationBeaconRequest.LinkStatus linkStatusForAttendanceArea = 5;</code>
   * @return The linkStatusForAttendanceArea.
   */
  @java.lang.Override public dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus getLinkStatusForAttendanceArea() {
    @SuppressWarnings("deprecation")
    dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus result = dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus.valueOf(linkStatusForAttendanceArea_);
    return result == null ? dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus.UNRECOGNIZED : result;
  }

  public static final int LINKSTATUSFORMRMANAGEMENTAREA_FIELD_NUMBER = 6;
  private int linkStatusForMrManagementArea_;
  /**
   * <pre>
   *&#47; ビーコンMr管理エリアとのリンク状態
   * </pre>
   *
   * <code>.registration.REListInstallationBeaconRequest.LinkStatus linkStatusForMrManagementArea = 6;</code>
   * @return The enum numeric value on the wire for linkStatusForMrManagementArea.
   */
  @java.lang.Override public int getLinkStatusForMrManagementAreaValue() {
    return linkStatusForMrManagementArea_;
  }
  /**
   * <pre>
   *&#47; ビーコンMr管理エリアとのリンク状態
   * </pre>
   *
   * <code>.registration.REListInstallationBeaconRequest.LinkStatus linkStatusForMrManagementArea = 6;</code>
   * @return The linkStatusForMrManagementArea.
   */
  @java.lang.Override public dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus getLinkStatusForMrManagementArea() {
    @SuppressWarnings("deprecation")
    dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus result = dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus.valueOf(linkStatusForMrManagementArea_);
    return result == null ? dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(keyword_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, keyword_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(officeId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, officeId_);
    }
    if (offset_ != 0) {
      output.writeInt32(3, offset_);
    }
    if (limit_ != 0) {
      output.writeInt32(4, limit_);
    }
    if (linkStatusForAttendanceArea_ != dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus.ONLY_LINKED.getNumber()) {
      output.writeEnum(5, linkStatusForAttendanceArea_);
    }
    if (linkStatusForMrManagementArea_ != dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus.ONLY_LINKED.getNumber()) {
      output.writeEnum(6, linkStatusForMrManagementArea_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(keyword_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, keyword_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(officeId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, officeId_);
    }
    if (offset_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, offset_);
    }
    if (limit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, limit_);
    }
    if (linkStatusForAttendanceArea_ != dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus.ONLY_LINKED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, linkStatusForAttendanceArea_);
    }
    if (linkStatusForMrManagementArea_ != dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus.ONLY_LINKED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, linkStatusForMrManagementArea_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest)) {
      return super.equals(obj);
    }
    dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest other = (dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest) obj;

    if (!getKeyword()
        .equals(other.getKeyword())) return false;
    if (!getOfficeId()
        .equals(other.getOfficeId())) return false;
    if (getOffset()
        != other.getOffset()) return false;
    if (getLimit()
        != other.getLimit()) return false;
    if (linkStatusForAttendanceArea_ != other.linkStatusForAttendanceArea_) return false;
    if (linkStatusForMrManagementArea_ != other.linkStatusForMrManagementArea_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEYWORD_FIELD_NUMBER;
    hash = (53 * hash) + getKeyword().hashCode();
    hash = (37 * hash) + OFFICEID_FIELD_NUMBER;
    hash = (53 * hash) + getOfficeId().hashCode();
    hash = (37 * hash) + OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + getOffset();
    hash = (37 * hash) + LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getLimit();
    hash = (37 * hash) + LINKSTATUSFORATTENDANCEAREA_FIELD_NUMBER;
    hash = (53 * hash) + linkStatusForAttendanceArea_;
    hash = (37 * hash) + LINKSTATUSFORMRMANAGEMENTAREA_FIELD_NUMBER;
    hash = (53 * hash) + linkStatusForMrManagementArea_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code registration.REListInstallationBeaconRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:registration.REListInstallationBeaconRequest)
      dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.internal_static_registration_REListInstallationBeaconRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.internal_static_registration_REListInstallationBeaconRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.class, dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.Builder.class);
    }

    // Construct using dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      keyword_ = "";

      officeId_ = "";

      offset_ = 0;

      limit_ = 0;

      linkStatusForAttendanceArea_ = 0;

      linkStatusForMrManagementArea_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.internal_static_registration_REListInstallationBeaconRequest_descriptor;
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest getDefaultInstanceForType() {
      return dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.getDefaultInstance();
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest build() {
      dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest buildPartial() {
      dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest result = new dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest(this);
      result.keyword_ = keyword_;
      result.officeId_ = officeId_;
      result.offset_ = offset_;
      result.limit_ = limit_;
      result.linkStatusForAttendanceArea_ = linkStatusForAttendanceArea_;
      result.linkStatusForMrManagementArea_ = linkStatusForMrManagementArea_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest) {
        return mergeFrom((dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest other) {
      if (other == dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.getDefaultInstance()) return this;
      if (!other.getKeyword().isEmpty()) {
        keyword_ = other.keyword_;
        onChanged();
      }
      if (!other.getOfficeId().isEmpty()) {
        officeId_ = other.officeId_;
        onChanged();
      }
      if (other.getOffset() != 0) {
        setOffset(other.getOffset());
      }
      if (other.getLimit() != 0) {
        setLimit(other.getLimit());
      }
      if (other.linkStatusForAttendanceArea_ != 0) {
        setLinkStatusForAttendanceAreaValue(other.getLinkStatusForAttendanceAreaValue());
      }
      if (other.linkStatusForMrManagementArea_ != 0) {
        setLinkStatusForMrManagementAreaValue(other.getLinkStatusForMrManagementAreaValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object keyword_ = "";
    /**
     * <pre>
     *&#47; 検索キーワード
     * </pre>
     *
     * <code>string keyword = 1;</code>
     * @return The keyword.
     */
    public java.lang.String getKeyword() {
      java.lang.Object ref = keyword_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyword_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; 検索キーワード
     * </pre>
     *
     * <code>string keyword = 1;</code>
     * @return The bytes for keyword.
     */
    public com.google.protobuf.ByteString
        getKeywordBytes() {
      java.lang.Object ref = keyword_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; 検索キーワード
     * </pre>
     *
     * <code>string keyword = 1;</code>
     * @param value The keyword to set.
     * @return This builder for chaining.
     */
    public Builder setKeyword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      keyword_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 検索キーワード
     * </pre>
     *
     * <code>string keyword = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyword() {
      
      keyword_ = getDefaultInstance().getKeyword();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 検索キーワード
     * </pre>
     *
     * <code>string keyword = 1;</code>
     * @param value The bytes for keyword to set.
     * @return This builder for chaining.
     */
    public Builder setKeywordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      keyword_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object officeId_ = "";
    /**
     * <pre>
     *&#47; 事業所ID
     * </pre>
     *
     * <code>string officeId = 2;</code>
     * @return The officeId.
     */
    public java.lang.String getOfficeId() {
      java.lang.Object ref = officeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        officeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; 事業所ID
     * </pre>
     *
     * <code>string officeId = 2;</code>
     * @return The bytes for officeId.
     */
    public com.google.protobuf.ByteString
        getOfficeIdBytes() {
      java.lang.Object ref = officeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        officeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; 事業所ID
     * </pre>
     *
     * <code>string officeId = 2;</code>
     * @param value The officeId to set.
     * @return This builder for chaining.
     */
    public Builder setOfficeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      officeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 事業所ID
     * </pre>
     *
     * <code>string officeId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOfficeId() {
      
      officeId_ = getDefaultInstance().getOfficeId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 事業所ID
     * </pre>
     *
     * <code>string officeId = 2;</code>
     * @param value The bytes for officeId to set.
     * @return This builder for chaining.
     */
    public Builder setOfficeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      officeId_ = value;
      onChanged();
      return this;
    }

    private int offset_ ;
    /**
     * <pre>
     *&#47; オフセット
     * </pre>
     *
     * <code>int32 offset = 3;</code>
     * @return The offset.
     */
    @java.lang.Override
    public int getOffset() {
      return offset_;
    }
    /**
     * <pre>
     *&#47; オフセット
     * </pre>
     *
     * <code>int32 offset = 3;</code>
     * @param value The offset to set.
     * @return This builder for chaining.
     */
    public Builder setOffset(int value) {
      
      offset_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; オフセット
     * </pre>
     *
     * <code>int32 offset = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOffset() {
      
      offset_ = 0;
      onChanged();
      return this;
    }

    private int limit_ ;
    /**
     * <pre>
     *&#47; 最大取得件数
     * </pre>
     *
     * <code>int32 limit = 4;</code>
     * @return The limit.
     */
    @java.lang.Override
    public int getLimit() {
      return limit_;
    }
    /**
     * <pre>
     *&#47; 最大取得件数
     * </pre>
     *
     * <code>int32 limit = 4;</code>
     * @param value The limit to set.
     * @return This builder for chaining.
     */
    public Builder setLimit(int value) {
      
      limit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 最大取得件数
     * </pre>
     *
     * <code>int32 limit = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimit() {
      
      limit_ = 0;
      onChanged();
      return this;
    }

    private int linkStatusForAttendanceArea_ = 0;
    /**
     * <pre>
     *&#47; ビーコン勤怠エリアとのリンク状態
     * </pre>
     *
     * <code>.registration.REListInstallationBeaconRequest.LinkStatus linkStatusForAttendanceArea = 5;</code>
     * @return The enum numeric value on the wire for linkStatusForAttendanceArea.
     */
    @java.lang.Override public int getLinkStatusForAttendanceAreaValue() {
      return linkStatusForAttendanceArea_;
    }
    /**
     * <pre>
     *&#47; ビーコン勤怠エリアとのリンク状態
     * </pre>
     *
     * <code>.registration.REListInstallationBeaconRequest.LinkStatus linkStatusForAttendanceArea = 5;</code>
     * @param value The enum numeric value on the wire for linkStatusForAttendanceArea to set.
     * @return This builder for chaining.
     */
    public Builder setLinkStatusForAttendanceAreaValue(int value) {
      
      linkStatusForAttendanceArea_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ビーコン勤怠エリアとのリンク状態
     * </pre>
     *
     * <code>.registration.REListInstallationBeaconRequest.LinkStatus linkStatusForAttendanceArea = 5;</code>
     * @return The linkStatusForAttendanceArea.
     */
    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus getLinkStatusForAttendanceArea() {
      @SuppressWarnings("deprecation")
      dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus result = dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus.valueOf(linkStatusForAttendanceArea_);
      return result == null ? dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *&#47; ビーコン勤怠エリアとのリンク状態
     * </pre>
     *
     * <code>.registration.REListInstallationBeaconRequest.LinkStatus linkStatusForAttendanceArea = 5;</code>
     * @param value The linkStatusForAttendanceArea to set.
     * @return This builder for chaining.
     */
    public Builder setLinkStatusForAttendanceArea(dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      linkStatusForAttendanceArea_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ビーコン勤怠エリアとのリンク状態
     * </pre>
     *
     * <code>.registration.REListInstallationBeaconRequest.LinkStatus linkStatusForAttendanceArea = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLinkStatusForAttendanceArea() {
      
      linkStatusForAttendanceArea_ = 0;
      onChanged();
      return this;
    }

    private int linkStatusForMrManagementArea_ = 0;
    /**
     * <pre>
     *&#47; ビーコンMr管理エリアとのリンク状態
     * </pre>
     *
     * <code>.registration.REListInstallationBeaconRequest.LinkStatus linkStatusForMrManagementArea = 6;</code>
     * @return The enum numeric value on the wire for linkStatusForMrManagementArea.
     */
    @java.lang.Override public int getLinkStatusForMrManagementAreaValue() {
      return linkStatusForMrManagementArea_;
    }
    /**
     * <pre>
     *&#47; ビーコンMr管理エリアとのリンク状態
     * </pre>
     *
     * <code>.registration.REListInstallationBeaconRequest.LinkStatus linkStatusForMrManagementArea = 6;</code>
     * @param value The enum numeric value on the wire for linkStatusForMrManagementArea to set.
     * @return This builder for chaining.
     */
    public Builder setLinkStatusForMrManagementAreaValue(int value) {
      
      linkStatusForMrManagementArea_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ビーコンMr管理エリアとのリンク状態
     * </pre>
     *
     * <code>.registration.REListInstallationBeaconRequest.LinkStatus linkStatusForMrManagementArea = 6;</code>
     * @return The linkStatusForMrManagementArea.
     */
    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus getLinkStatusForMrManagementArea() {
      @SuppressWarnings("deprecation")
      dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus result = dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus.valueOf(linkStatusForMrManagementArea_);
      return result == null ? dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *&#47; ビーコンMr管理エリアとのリンク状態
     * </pre>
     *
     * <code>.registration.REListInstallationBeaconRequest.LinkStatus linkStatusForMrManagementArea = 6;</code>
     * @param value The linkStatusForMrManagementArea to set.
     * @return This builder for chaining.
     */
    public Builder setLinkStatusForMrManagementArea(dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest.LinkStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      linkStatusForMrManagementArea_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ビーコンMr管理エリアとのリンク状態
     * </pre>
     *
     * <code>.registration.REListInstallationBeaconRequest.LinkStatus linkStatusForMrManagementArea = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLinkStatusForMrManagementArea() {
      
      linkStatusForMrManagementArea_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:registration.REListInstallationBeaconRequest)
  }

  // @@protoc_insertion_point(class_scope:registration.REListInstallationBeaconRequest)
  private static final dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest();
  }

  public static dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<REListInstallationBeaconRequest>
      PARSER = new com.google.protobuf.AbstractParser<REListInstallationBeaconRequest>() {
    @java.lang.Override
    public REListInstallationBeaconRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new REListInstallationBeaconRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<REListInstallationBeaconRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<REListInstallationBeaconRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dr.app.core.autogen.grpc.registration.REListInstallationBeaconRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

