// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration.proto

package dr.app.core.autogen.grpc.registration;

public interface REListBeaconAreaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registration.REListBeaconAreaRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *&#47; 検索キーワード
   * </pre>
   *
   * <code>string keyword = 1;</code>
   * @return The keyword.
   */
  java.lang.String getKeyword();
  /**
   * <pre>
   *&#47; 検索キーワード
   * </pre>
   *
   * <code>string keyword = 1;</code>
   * @return The bytes for keyword.
   */
  com.google.protobuf.ByteString
      getKeywordBytes();

  /**
   * <pre>
   *&#47; 事業所ID
   * </pre>
   *
   * <code>string officeId = 2;</code>
   * @return The officeId.
   */
  java.lang.String getOfficeId();
  /**
   * <pre>
   *&#47; 事業所ID
   * </pre>
   *
   * <code>string officeId = 2;</code>
   * @return The bytes for officeId.
   */
  com.google.protobuf.ByteString
      getOfficeIdBytes();

  /**
   * <pre>
   *&#47; オフセット
   * </pre>
   *
   * <code>int32 offset = 3;</code>
   * @return The offset.
   */
  int getOffset();

  /**
   * <pre>
   *&#47; 最大取得件数
   * </pre>
   *
   * <code>int32 limit = 4;</code>
   * @return The limit.
   */
  int getLimit();
}
