// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration.proto

package dr.app.core.autogen.grpc.registration;

public interface REListBeaconAttendanceAreaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registration.REListBeaconAttendanceAreaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *&#47; 全件数
   * </pre>
   *
   * <code>int64 allCount = 1;</code>
   * @return The allCount.
   */
  long getAllCount();

  /**
   * <pre>
   *&#47; REBeaconAttendanceAreaのリスト
   * </pre>
   *
   * <code>repeated .registration.REBeaconAttendanceArea beaconAttendanceArea = 2;</code>
   */
  java.util.List<dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea> 
      getBeaconAttendanceAreaList();
  /**
   * <pre>
   *&#47; REBeaconAttendanceAreaのリスト
   * </pre>
   *
   * <code>repeated .registration.REBeaconAttendanceArea beaconAttendanceArea = 2;</code>
   */
  dr.app.core.autogen.grpc.registration.REBeaconAttendanceArea getBeaconAttendanceArea(int index);
  /**
   * <pre>
   *&#47; REBeaconAttendanceAreaのリスト
   * </pre>
   *
   * <code>repeated .registration.REBeaconAttendanceArea beaconAttendanceArea = 2;</code>
   */
  int getBeaconAttendanceAreaCount();
  /**
   * <pre>
   *&#47; REBeaconAttendanceAreaのリスト
   * </pre>
   *
   * <code>repeated .registration.REBeaconAttendanceArea beaconAttendanceArea = 2;</code>
   */
  java.util.List<? extends dr.app.core.autogen.grpc.registration.REBeaconAttendanceAreaOrBuilder> 
      getBeaconAttendanceAreaOrBuilderList();
  /**
   * <pre>
   *&#47; REBeaconAttendanceAreaのリスト
   * </pre>
   *
   * <code>repeated .registration.REBeaconAttendanceArea beaconAttendanceArea = 2;</code>
   */
  dr.app.core.autogen.grpc.registration.REBeaconAttendanceAreaOrBuilder getBeaconAttendanceAreaOrBuilder(
      int index);

  /**
   * <pre>
   *&#47; どのエリアにも紐づいていないビーコンの数
   * </pre>
   *
   * <code>int32 notLinkedBeaconCount = 3;</code>
   * @return The notLinkedBeaconCount.
   */
  int getNotLinkedBeaconCount();
}
