// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration_auth.proto

package dr.app.core.autogen.grpc.registration;

/**
 * Protobuf type {@code registration.RELoginUserResponse}
 */
public final class RELoginUserResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:registration.RELoginUserResponse)
    RELoginUserResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RELoginUserResponse.newBuilder() to construct.
  private RELoginUserResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RELoginUserResponse() {
    userId_ = "";
    loginId_ = "";
    password_ = "";
    officeId_ = "";
    officeUserId_ = "";
    managementAuthority_ = 0;
    officeType_ = 0;
    roleCodes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RELoginUserResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RELoginUserResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            loginId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            officeId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            officeUserId_ = s;
            break;
          }
          case 48: {

            accountStatuses_ = input.readInt32();
            break;
          }
          case 56: {
            int rawValue = input.readEnum();

            managementAuthority_ = rawValue;
            break;
          }
          case 80: {
            int rawValue = input.readEnum();

            officeType_ = rawValue;
            break;
          }
          case 88: {

            personalFlag_ = input.readBool();
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              roleCodes_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            roleCodes_.add(s);
            break;
          }
          case 104: {

            officeSessionExpiration_ = input.readInt64();
            break;
          }
          case 112: {

            twoFactorAuthenticationEnabled_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        roleCodes_ = roleCodes_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dr.app.core.autogen.grpc.registration.RegistrationAuthOuterClass.internal_static_registration_RELoginUserResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dr.app.core.autogen.grpc.registration.RegistrationAuthOuterClass.internal_static_registration_RELoginUserResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dr.app.core.autogen.grpc.registration.RELoginUserResponse.class, dr.app.core.autogen.grpc.registration.RELoginUserResponse.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private volatile java.lang.Object userId_;
  /**
   * <pre>
   *&#47; ユーザーID
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; ユーザーID
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOGINID_FIELD_NUMBER = 2;
  private volatile java.lang.Object loginId_;
  /**
   * <pre>
   *&#47; ログインID
   * </pre>
   *
   * <code>string loginId = 2;</code>
   * @return The loginId.
   */
  @java.lang.Override
  public java.lang.String getLoginId() {
    java.lang.Object ref = loginId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      loginId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; ログインID
   * </pre>
   *
   * <code>string loginId = 2;</code>
   * @return The bytes for loginId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLoginIdBytes() {
    java.lang.Object ref = loginId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      loginId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 3;
  private volatile java.lang.Object password_;
  /**
   * <pre>
   *&#47; パスワード(クイックログインの時はクイックトークン)
   * </pre>
   *
   * <code>string password = 3;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; パスワード(クイックログインの時はクイックトークン)
   * </pre>
   *
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OFFICEID_FIELD_NUMBER = 4;
  private volatile java.lang.Object officeId_;
  /**
   * <pre>
   *&#47; オフィスID
   * </pre>
   *
   * <code>string officeId = 4;</code>
   * @return The officeId.
   */
  @java.lang.Override
  public java.lang.String getOfficeId() {
    java.lang.Object ref = officeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      officeId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; オフィスID
   * </pre>
   *
   * <code>string officeId = 4;</code>
   * @return The bytes for officeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOfficeIdBytes() {
    java.lang.Object ref = officeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      officeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OFFICEUSERID_FIELD_NUMBER = 5;
  private volatile java.lang.Object officeUserId_;
  /**
   * <pre>
   *&#47; 事業所ユーザID
   * </pre>
   *
   * <code>string officeUserId = 5;</code>
   * @return The officeUserId.
   */
  @java.lang.Override
  public java.lang.String getOfficeUserId() {
    java.lang.Object ref = officeUserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      officeUserId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; 事業所ユーザID
   * </pre>
   *
   * <code>string officeUserId = 5;</code>
   * @return The bytes for officeUserId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOfficeUserIdBytes() {
    java.lang.Object ref = officeUserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      officeUserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNTSTATUSES_FIELD_NUMBER = 6;
  private int accountStatuses_;
  /**
   * <pre>
   *&#47; アカウントステータス
   * </pre>
   *
   * <code>int32 accountStatuses = 6;</code>
   * @return The accountStatuses.
   */
  @java.lang.Override
  public int getAccountStatuses() {
    return accountStatuses_;
  }

  public static final int MANAGEMENTAUTHORITY_FIELD_NUMBER = 7;
  private int managementAuthority_;
  /**
   * <pre>
   *&#47; 管理権限
   * </pre>
   *
   * <code>.registration.REManagementAuthority managementAuthority = 7;</code>
   * @return The enum numeric value on the wire for managementAuthority.
   */
  @java.lang.Override public int getManagementAuthorityValue() {
    return managementAuthority_;
  }
  /**
   * <pre>
   *&#47; 管理権限
   * </pre>
   *
   * <code>.registration.REManagementAuthority managementAuthority = 7;</code>
   * @return The managementAuthority.
   */
  @java.lang.Override public dr.app.core.autogen.grpc.registration.REManagementAuthority getManagementAuthority() {
    @SuppressWarnings("deprecation")
    dr.app.core.autogen.grpc.registration.REManagementAuthority result = dr.app.core.autogen.grpc.registration.REManagementAuthority.valueOf(managementAuthority_);
    return result == null ? dr.app.core.autogen.grpc.registration.REManagementAuthority.UNRECOGNIZED : result;
  }

  public static final int OFFICETYPE_FIELD_NUMBER = 10;
  private int officeType_;
  /**
   * <pre>
   *&#47; オフィスタイプ
   * </pre>
   *
   * <code>.registration.REOfficeType officeType = 10;</code>
   * @return The enum numeric value on the wire for officeType.
   */
  @java.lang.Override public int getOfficeTypeValue() {
    return officeType_;
  }
  /**
   * <pre>
   *&#47; オフィスタイプ
   * </pre>
   *
   * <code>.registration.REOfficeType officeType = 10;</code>
   * @return The officeType.
   */
  @java.lang.Override public dr.app.core.autogen.grpc.registration.REOfficeType getOfficeType() {
    @SuppressWarnings("deprecation")
    dr.app.core.autogen.grpc.registration.REOfficeType result = dr.app.core.autogen.grpc.registration.REOfficeType.valueOf(officeType_);
    return result == null ? dr.app.core.autogen.grpc.registration.REOfficeType.UNRECOGNIZED : result;
  }

  public static final int PERSONALFLAG_FIELD_NUMBER = 11;
  private boolean personalFlag_;
  /**
   * <pre>
   *&#47; personal flag
   * </pre>
   *
   * <code>bool personalFlag = 11;</code>
   * @return The personalFlag.
   */
  @java.lang.Override
  public boolean getPersonalFlag() {
    return personalFlag_;
  }

  public static final int ROLECODES_FIELD_NUMBER = 12;
  private com.google.protobuf.LazyStringList roleCodes_;
  /**
   * <pre>
   *&#47; ロール
   * </pre>
   *
   * <code>repeated string roleCodes = 12;</code>
   * @return A list containing the roleCodes.
   */
  public com.google.protobuf.ProtocolStringList
      getRoleCodesList() {
    return roleCodes_;
  }
  /**
   * <pre>
   *&#47; ロール
   * </pre>
   *
   * <code>repeated string roleCodes = 12;</code>
   * @return The count of roleCodes.
   */
  public int getRoleCodesCount() {
    return roleCodes_.size();
  }
  /**
   * <pre>
   *&#47; ロール
   * </pre>
   *
   * <code>repeated string roleCodes = 12;</code>
   * @param index The index of the element to return.
   * @return The roleCodes at the given index.
   */
  public java.lang.String getRoleCodes(int index) {
    return roleCodes_.get(index);
  }
  /**
   * <pre>
   *&#47; ロール
   * </pre>
   *
   * <code>repeated string roleCodes = 12;</code>
   * @param index The index of the value to return.
   * @return The bytes of the roleCodes at the given index.
   */
  public com.google.protobuf.ByteString
      getRoleCodesBytes(int index) {
    return roleCodes_.getByteString(index);
  }

  public static final int OFFICESESSIONEXPIRATION_FIELD_NUMBER = 13;
  private long officeSessionExpiration_;
  /**
   * <pre>
   *&#47; オフィス毎のセッション有効期限
   * </pre>
   *
   * <code>int64 officeSessionExpiration = 13;</code>
   * @return The officeSessionExpiration.
   */
  @java.lang.Override
  public long getOfficeSessionExpiration() {
    return officeSessionExpiration_;
  }

  public static final int TWOFACTORAUTHENTICATIONENABLED_FIELD_NUMBER = 14;
  private boolean twoFactorAuthenticationEnabled_;
  /**
   * <pre>
   *&#47; 二要素認証有効化フラグ
   * </pre>
   *
   * <code>bool twoFactorAuthenticationEnabled = 14;</code>
   * @return The twoFactorAuthenticationEnabled.
   */
  @java.lang.Override
  public boolean getTwoFactorAuthenticationEnabled() {
    return twoFactorAuthenticationEnabled_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(loginId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, loginId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(officeId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, officeId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(officeUserId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, officeUserId_);
    }
    if (accountStatuses_ != 0) {
      output.writeInt32(6, accountStatuses_);
    }
    if (managementAuthority_ != dr.app.core.autogen.grpc.registration.REManagementAuthority.MP_1.getNumber()) {
      output.writeEnum(7, managementAuthority_);
    }
    if (officeType_ != dr.app.core.autogen.grpc.registration.REOfficeType.MEDICAL.getNumber()) {
      output.writeEnum(10, officeType_);
    }
    if (personalFlag_ != false) {
      output.writeBool(11, personalFlag_);
    }
    for (int i = 0; i < roleCodes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, roleCodes_.getRaw(i));
    }
    if (officeSessionExpiration_ != 0L) {
      output.writeInt64(13, officeSessionExpiration_);
    }
    if (twoFactorAuthenticationEnabled_ != false) {
      output.writeBool(14, twoFactorAuthenticationEnabled_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(loginId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, loginId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(officeId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, officeId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(officeUserId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, officeUserId_);
    }
    if (accountStatuses_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, accountStatuses_);
    }
    if (managementAuthority_ != dr.app.core.autogen.grpc.registration.REManagementAuthority.MP_1.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, managementAuthority_);
    }
    if (officeType_ != dr.app.core.autogen.grpc.registration.REOfficeType.MEDICAL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, officeType_);
    }
    if (personalFlag_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, personalFlag_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < roleCodes_.size(); i++) {
        dataSize += computeStringSizeNoTag(roleCodes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRoleCodesList().size();
    }
    if (officeSessionExpiration_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, officeSessionExpiration_);
    }
    if (twoFactorAuthenticationEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, twoFactorAuthenticationEnabled_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dr.app.core.autogen.grpc.registration.RELoginUserResponse)) {
      return super.equals(obj);
    }
    dr.app.core.autogen.grpc.registration.RELoginUserResponse other = (dr.app.core.autogen.grpc.registration.RELoginUserResponse) obj;

    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (!getLoginId()
        .equals(other.getLoginId())) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (!getOfficeId()
        .equals(other.getOfficeId())) return false;
    if (!getOfficeUserId()
        .equals(other.getOfficeUserId())) return false;
    if (getAccountStatuses()
        != other.getAccountStatuses()) return false;
    if (managementAuthority_ != other.managementAuthority_) return false;
    if (officeType_ != other.officeType_) return false;
    if (getPersonalFlag()
        != other.getPersonalFlag()) return false;
    if (!getRoleCodesList()
        .equals(other.getRoleCodesList())) return false;
    if (getOfficeSessionExpiration()
        != other.getOfficeSessionExpiration()) return false;
    if (getTwoFactorAuthenticationEnabled()
        != other.getTwoFactorAuthenticationEnabled()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + LOGINID_FIELD_NUMBER;
    hash = (53 * hash) + getLoginId().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (37 * hash) + OFFICEID_FIELD_NUMBER;
    hash = (53 * hash) + getOfficeId().hashCode();
    hash = (37 * hash) + OFFICEUSERID_FIELD_NUMBER;
    hash = (53 * hash) + getOfficeUserId().hashCode();
    hash = (37 * hash) + ACCOUNTSTATUSES_FIELD_NUMBER;
    hash = (53 * hash) + getAccountStatuses();
    hash = (37 * hash) + MANAGEMENTAUTHORITY_FIELD_NUMBER;
    hash = (53 * hash) + managementAuthority_;
    hash = (37 * hash) + OFFICETYPE_FIELD_NUMBER;
    hash = (53 * hash) + officeType_;
    hash = (37 * hash) + PERSONALFLAG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPersonalFlag());
    if (getRoleCodesCount() > 0) {
      hash = (37 * hash) + ROLECODES_FIELD_NUMBER;
      hash = (53 * hash) + getRoleCodesList().hashCode();
    }
    hash = (37 * hash) + OFFICESESSIONEXPIRATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOfficeSessionExpiration());
    hash = (37 * hash) + TWOFACTORAUTHENTICATIONENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTwoFactorAuthenticationEnabled());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dr.app.core.autogen.grpc.registration.RELoginUserResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.RELoginUserResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.RELoginUserResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.RELoginUserResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.RELoginUserResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.RELoginUserResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.RELoginUserResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.RELoginUserResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.RELoginUserResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.RELoginUserResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.RELoginUserResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.RELoginUserResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dr.app.core.autogen.grpc.registration.RELoginUserResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code registration.RELoginUserResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:registration.RELoginUserResponse)
      dr.app.core.autogen.grpc.registration.RELoginUserResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dr.app.core.autogen.grpc.registration.RegistrationAuthOuterClass.internal_static_registration_RELoginUserResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dr.app.core.autogen.grpc.registration.RegistrationAuthOuterClass.internal_static_registration_RELoginUserResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dr.app.core.autogen.grpc.registration.RELoginUserResponse.class, dr.app.core.autogen.grpc.registration.RELoginUserResponse.Builder.class);
    }

    // Construct using dr.app.core.autogen.grpc.registration.RELoginUserResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userId_ = "";

      loginId_ = "";

      password_ = "";

      officeId_ = "";

      officeUserId_ = "";

      accountStatuses_ = 0;

      managementAuthority_ = 0;

      officeType_ = 0;

      personalFlag_ = false;

      roleCodes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      officeSessionExpiration_ = 0L;

      twoFactorAuthenticationEnabled_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dr.app.core.autogen.grpc.registration.RegistrationAuthOuterClass.internal_static_registration_RELoginUserResponse_descriptor;
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.RELoginUserResponse getDefaultInstanceForType() {
      return dr.app.core.autogen.grpc.registration.RELoginUserResponse.getDefaultInstance();
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.RELoginUserResponse build() {
      dr.app.core.autogen.grpc.registration.RELoginUserResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.RELoginUserResponse buildPartial() {
      dr.app.core.autogen.grpc.registration.RELoginUserResponse result = new dr.app.core.autogen.grpc.registration.RELoginUserResponse(this);
      int from_bitField0_ = bitField0_;
      result.userId_ = userId_;
      result.loginId_ = loginId_;
      result.password_ = password_;
      result.officeId_ = officeId_;
      result.officeUserId_ = officeUserId_;
      result.accountStatuses_ = accountStatuses_;
      result.managementAuthority_ = managementAuthority_;
      result.officeType_ = officeType_;
      result.personalFlag_ = personalFlag_;
      if (((bitField0_ & 0x00000001) != 0)) {
        roleCodes_ = roleCodes_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.roleCodes_ = roleCodes_;
      result.officeSessionExpiration_ = officeSessionExpiration_;
      result.twoFactorAuthenticationEnabled_ = twoFactorAuthenticationEnabled_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dr.app.core.autogen.grpc.registration.RELoginUserResponse) {
        return mergeFrom((dr.app.core.autogen.grpc.registration.RELoginUserResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dr.app.core.autogen.grpc.registration.RELoginUserResponse other) {
      if (other == dr.app.core.autogen.grpc.registration.RELoginUserResponse.getDefaultInstance()) return this;
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (!other.getLoginId().isEmpty()) {
        loginId_ = other.loginId_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (!other.getOfficeId().isEmpty()) {
        officeId_ = other.officeId_;
        onChanged();
      }
      if (!other.getOfficeUserId().isEmpty()) {
        officeUserId_ = other.officeUserId_;
        onChanged();
      }
      if (other.getAccountStatuses() != 0) {
        setAccountStatuses(other.getAccountStatuses());
      }
      if (other.managementAuthority_ != 0) {
        setManagementAuthorityValue(other.getManagementAuthorityValue());
      }
      if (other.officeType_ != 0) {
        setOfficeTypeValue(other.getOfficeTypeValue());
      }
      if (other.getPersonalFlag() != false) {
        setPersonalFlag(other.getPersonalFlag());
      }
      if (!other.roleCodes_.isEmpty()) {
        if (roleCodes_.isEmpty()) {
          roleCodes_ = other.roleCodes_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureRoleCodesIsMutable();
          roleCodes_.addAll(other.roleCodes_);
        }
        onChanged();
      }
      if (other.getOfficeSessionExpiration() != 0L) {
        setOfficeSessionExpiration(other.getOfficeSessionExpiration());
      }
      if (other.getTwoFactorAuthenticationEnabled() != false) {
        setTwoFactorAuthenticationEnabled(other.getTwoFactorAuthenticationEnabled());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dr.app.core.autogen.grpc.registration.RELoginUserResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dr.app.core.autogen.grpc.registration.RELoginUserResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object userId_ = "";
    /**
     * <pre>
     *&#47; ユーザーID
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; ユーザーID
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; ユーザーID
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ユーザーID
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ユーザーID
     * </pre>
     *
     * <code>string userId = 1;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object loginId_ = "";
    /**
     * <pre>
     *&#47; ログインID
     * </pre>
     *
     * <code>string loginId = 2;</code>
     * @return The loginId.
     */
    public java.lang.String getLoginId() {
      java.lang.Object ref = loginId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loginId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; ログインID
     * </pre>
     *
     * <code>string loginId = 2;</code>
     * @return The bytes for loginId.
     */
    public com.google.protobuf.ByteString
        getLoginIdBytes() {
      java.lang.Object ref = loginId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; ログインID
     * </pre>
     *
     * <code>string loginId = 2;</code>
     * @param value The loginId to set.
     * @return This builder for chaining.
     */
    public Builder setLoginId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      loginId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ログインID
     * </pre>
     *
     * <code>string loginId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoginId() {
      
      loginId_ = getDefaultInstance().getLoginId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ログインID
     * </pre>
     *
     * <code>string loginId = 2;</code>
     * @param value The bytes for loginId to set.
     * @return This builder for chaining.
     */
    public Builder setLoginIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      loginId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <pre>
     *&#47; パスワード(クイックログインの時はクイックトークン)
     * </pre>
     *
     * <code>string password = 3;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; パスワード(クイックログインの時はクイックトークン)
     * </pre>
     *
     * <code>string password = 3;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; パスワード(クイックログインの時はクイックトークン)
     * </pre>
     *
     * <code>string password = 3;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; パスワード(クイックログインの時はクイックトークン)
     * </pre>
     *
     * <code>string password = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; パスワード(クイックログインの時はクイックトークン)
     * </pre>
     *
     * <code>string password = 3;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object officeId_ = "";
    /**
     * <pre>
     *&#47; オフィスID
     * </pre>
     *
     * <code>string officeId = 4;</code>
     * @return The officeId.
     */
    public java.lang.String getOfficeId() {
      java.lang.Object ref = officeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        officeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; オフィスID
     * </pre>
     *
     * <code>string officeId = 4;</code>
     * @return The bytes for officeId.
     */
    public com.google.protobuf.ByteString
        getOfficeIdBytes() {
      java.lang.Object ref = officeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        officeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; オフィスID
     * </pre>
     *
     * <code>string officeId = 4;</code>
     * @param value The officeId to set.
     * @return This builder for chaining.
     */
    public Builder setOfficeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      officeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; オフィスID
     * </pre>
     *
     * <code>string officeId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOfficeId() {
      
      officeId_ = getDefaultInstance().getOfficeId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; オフィスID
     * </pre>
     *
     * <code>string officeId = 4;</code>
     * @param value The bytes for officeId to set.
     * @return This builder for chaining.
     */
    public Builder setOfficeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      officeId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object officeUserId_ = "";
    /**
     * <pre>
     *&#47; 事業所ユーザID
     * </pre>
     *
     * <code>string officeUserId = 5;</code>
     * @return The officeUserId.
     */
    public java.lang.String getOfficeUserId() {
      java.lang.Object ref = officeUserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        officeUserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; 事業所ユーザID
     * </pre>
     *
     * <code>string officeUserId = 5;</code>
     * @return The bytes for officeUserId.
     */
    public com.google.protobuf.ByteString
        getOfficeUserIdBytes() {
      java.lang.Object ref = officeUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        officeUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; 事業所ユーザID
     * </pre>
     *
     * <code>string officeUserId = 5;</code>
     * @param value The officeUserId to set.
     * @return This builder for chaining.
     */
    public Builder setOfficeUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      officeUserId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 事業所ユーザID
     * </pre>
     *
     * <code>string officeUserId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOfficeUserId() {
      
      officeUserId_ = getDefaultInstance().getOfficeUserId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 事業所ユーザID
     * </pre>
     *
     * <code>string officeUserId = 5;</code>
     * @param value The bytes for officeUserId to set.
     * @return This builder for chaining.
     */
    public Builder setOfficeUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      officeUserId_ = value;
      onChanged();
      return this;
    }

    private int accountStatuses_ ;
    /**
     * <pre>
     *&#47; アカウントステータス
     * </pre>
     *
     * <code>int32 accountStatuses = 6;</code>
     * @return The accountStatuses.
     */
    @java.lang.Override
    public int getAccountStatuses() {
      return accountStatuses_;
    }
    /**
     * <pre>
     *&#47; アカウントステータス
     * </pre>
     *
     * <code>int32 accountStatuses = 6;</code>
     * @param value The accountStatuses to set.
     * @return This builder for chaining.
     */
    public Builder setAccountStatuses(int value) {
      
      accountStatuses_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; アカウントステータス
     * </pre>
     *
     * <code>int32 accountStatuses = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountStatuses() {
      
      accountStatuses_ = 0;
      onChanged();
      return this;
    }

    private int managementAuthority_ = 0;
    /**
     * <pre>
     *&#47; 管理権限
     * </pre>
     *
     * <code>.registration.REManagementAuthority managementAuthority = 7;</code>
     * @return The enum numeric value on the wire for managementAuthority.
     */
    @java.lang.Override public int getManagementAuthorityValue() {
      return managementAuthority_;
    }
    /**
     * <pre>
     *&#47; 管理権限
     * </pre>
     *
     * <code>.registration.REManagementAuthority managementAuthority = 7;</code>
     * @param value The enum numeric value on the wire for managementAuthority to set.
     * @return This builder for chaining.
     */
    public Builder setManagementAuthorityValue(int value) {
      
      managementAuthority_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 管理権限
     * </pre>
     *
     * <code>.registration.REManagementAuthority managementAuthority = 7;</code>
     * @return The managementAuthority.
     */
    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REManagementAuthority getManagementAuthority() {
      @SuppressWarnings("deprecation")
      dr.app.core.autogen.grpc.registration.REManagementAuthority result = dr.app.core.autogen.grpc.registration.REManagementAuthority.valueOf(managementAuthority_);
      return result == null ? dr.app.core.autogen.grpc.registration.REManagementAuthority.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *&#47; 管理権限
     * </pre>
     *
     * <code>.registration.REManagementAuthority managementAuthority = 7;</code>
     * @param value The managementAuthority to set.
     * @return This builder for chaining.
     */
    public Builder setManagementAuthority(dr.app.core.autogen.grpc.registration.REManagementAuthority value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      managementAuthority_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 管理権限
     * </pre>
     *
     * <code>.registration.REManagementAuthority managementAuthority = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearManagementAuthority() {
      
      managementAuthority_ = 0;
      onChanged();
      return this;
    }

    private int officeType_ = 0;
    /**
     * <pre>
     *&#47; オフィスタイプ
     * </pre>
     *
     * <code>.registration.REOfficeType officeType = 10;</code>
     * @return The enum numeric value on the wire for officeType.
     */
    @java.lang.Override public int getOfficeTypeValue() {
      return officeType_;
    }
    /**
     * <pre>
     *&#47; オフィスタイプ
     * </pre>
     *
     * <code>.registration.REOfficeType officeType = 10;</code>
     * @param value The enum numeric value on the wire for officeType to set.
     * @return This builder for chaining.
     */
    public Builder setOfficeTypeValue(int value) {
      
      officeType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; オフィスタイプ
     * </pre>
     *
     * <code>.registration.REOfficeType officeType = 10;</code>
     * @return The officeType.
     */
    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REOfficeType getOfficeType() {
      @SuppressWarnings("deprecation")
      dr.app.core.autogen.grpc.registration.REOfficeType result = dr.app.core.autogen.grpc.registration.REOfficeType.valueOf(officeType_);
      return result == null ? dr.app.core.autogen.grpc.registration.REOfficeType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *&#47; オフィスタイプ
     * </pre>
     *
     * <code>.registration.REOfficeType officeType = 10;</code>
     * @param value The officeType to set.
     * @return This builder for chaining.
     */
    public Builder setOfficeType(dr.app.core.autogen.grpc.registration.REOfficeType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      officeType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; オフィスタイプ
     * </pre>
     *
     * <code>.registration.REOfficeType officeType = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearOfficeType() {
      
      officeType_ = 0;
      onChanged();
      return this;
    }

    private boolean personalFlag_ ;
    /**
     * <pre>
     *&#47; personal flag
     * </pre>
     *
     * <code>bool personalFlag = 11;</code>
     * @return The personalFlag.
     */
    @java.lang.Override
    public boolean getPersonalFlag() {
      return personalFlag_;
    }
    /**
     * <pre>
     *&#47; personal flag
     * </pre>
     *
     * <code>bool personalFlag = 11;</code>
     * @param value The personalFlag to set.
     * @return This builder for chaining.
     */
    public Builder setPersonalFlag(boolean value) {
      
      personalFlag_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; personal flag
     * </pre>
     *
     * <code>bool personalFlag = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearPersonalFlag() {
      
      personalFlag_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList roleCodes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureRoleCodesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        roleCodes_ = new com.google.protobuf.LazyStringArrayList(roleCodes_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     *&#47; ロール
     * </pre>
     *
     * <code>repeated string roleCodes = 12;</code>
     * @return A list containing the roleCodes.
     */
    public com.google.protobuf.ProtocolStringList
        getRoleCodesList() {
      return roleCodes_.getUnmodifiableView();
    }
    /**
     * <pre>
     *&#47; ロール
     * </pre>
     *
     * <code>repeated string roleCodes = 12;</code>
     * @return The count of roleCodes.
     */
    public int getRoleCodesCount() {
      return roleCodes_.size();
    }
    /**
     * <pre>
     *&#47; ロール
     * </pre>
     *
     * <code>repeated string roleCodes = 12;</code>
     * @param index The index of the element to return.
     * @return The roleCodes at the given index.
     */
    public java.lang.String getRoleCodes(int index) {
      return roleCodes_.get(index);
    }
    /**
     * <pre>
     *&#47; ロール
     * </pre>
     *
     * <code>repeated string roleCodes = 12;</code>
     * @param index The index of the value to return.
     * @return The bytes of the roleCodes at the given index.
     */
    public com.google.protobuf.ByteString
        getRoleCodesBytes(int index) {
      return roleCodes_.getByteString(index);
    }
    /**
     * <pre>
     *&#47; ロール
     * </pre>
     *
     * <code>repeated string roleCodes = 12;</code>
     * @param index The index to set the value at.
     * @param value The roleCodes to set.
     * @return This builder for chaining.
     */
    public Builder setRoleCodes(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRoleCodesIsMutable();
      roleCodes_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ロール
     * </pre>
     *
     * <code>repeated string roleCodes = 12;</code>
     * @param value The roleCodes to add.
     * @return This builder for chaining.
     */
    public Builder addRoleCodes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRoleCodesIsMutable();
      roleCodes_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ロール
     * </pre>
     *
     * <code>repeated string roleCodes = 12;</code>
     * @param values The roleCodes to add.
     * @return This builder for chaining.
     */
    public Builder addAllRoleCodes(
        java.lang.Iterable<java.lang.String> values) {
      ensureRoleCodesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, roleCodes_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ロール
     * </pre>
     *
     * <code>repeated string roleCodes = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoleCodes() {
      roleCodes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ロール
     * </pre>
     *
     * <code>repeated string roleCodes = 12;</code>
     * @param value The bytes of the roleCodes to add.
     * @return This builder for chaining.
     */
    public Builder addRoleCodesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureRoleCodesIsMutable();
      roleCodes_.add(value);
      onChanged();
      return this;
    }

    private long officeSessionExpiration_ ;
    /**
     * <pre>
     *&#47; オフィス毎のセッション有効期限
     * </pre>
     *
     * <code>int64 officeSessionExpiration = 13;</code>
     * @return The officeSessionExpiration.
     */
    @java.lang.Override
    public long getOfficeSessionExpiration() {
      return officeSessionExpiration_;
    }
    /**
     * <pre>
     *&#47; オフィス毎のセッション有効期限
     * </pre>
     *
     * <code>int64 officeSessionExpiration = 13;</code>
     * @param value The officeSessionExpiration to set.
     * @return This builder for chaining.
     */
    public Builder setOfficeSessionExpiration(long value) {
      
      officeSessionExpiration_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; オフィス毎のセッション有効期限
     * </pre>
     *
     * <code>int64 officeSessionExpiration = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearOfficeSessionExpiration() {
      
      officeSessionExpiration_ = 0L;
      onChanged();
      return this;
    }

    private boolean twoFactorAuthenticationEnabled_ ;
    /**
     * <pre>
     *&#47; 二要素認証有効化フラグ
     * </pre>
     *
     * <code>bool twoFactorAuthenticationEnabled = 14;</code>
     * @return The twoFactorAuthenticationEnabled.
     */
    @java.lang.Override
    public boolean getTwoFactorAuthenticationEnabled() {
      return twoFactorAuthenticationEnabled_;
    }
    /**
     * <pre>
     *&#47; 二要素認証有効化フラグ
     * </pre>
     *
     * <code>bool twoFactorAuthenticationEnabled = 14;</code>
     * @param value The twoFactorAuthenticationEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setTwoFactorAuthenticationEnabled(boolean value) {
      
      twoFactorAuthenticationEnabled_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 二要素認証有効化フラグ
     * </pre>
     *
     * <code>bool twoFactorAuthenticationEnabled = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearTwoFactorAuthenticationEnabled() {
      
      twoFactorAuthenticationEnabled_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:registration.RELoginUserResponse)
  }

  // @@protoc_insertion_point(class_scope:registration.RELoginUserResponse)
  private static final dr.app.core.autogen.grpc.registration.RELoginUserResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dr.app.core.autogen.grpc.registration.RELoginUserResponse();
  }

  public static dr.app.core.autogen.grpc.registration.RELoginUserResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RELoginUserResponse>
      PARSER = new com.google.protobuf.AbstractParser<RELoginUserResponse>() {
    @java.lang.Override
    public RELoginUserResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RELoginUserResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RELoginUserResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RELoginUserResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dr.app.core.autogen.grpc.registration.RELoginUserResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

