// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration_auth.proto

package dr.app.core.autogen.grpc.registration;

public interface RELoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registration.RELoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *&#47; ログインID
   * </pre>
   *
   * <code>string loginId = 1;</code>
   * @return The loginId.
   */
  java.lang.String getLoginId();
  /**
   * <pre>
   *&#47; ログインID
   * </pre>
   *
   * <code>string loginId = 1;</code>
   * @return The bytes for loginId.
   */
  com.google.protobuf.ByteString
      getLoginIdBytes();
}
