// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration.proto

package dr.app.core.autogen.grpc.registration;

/**
 * <pre>
 **
 * 管理権限
 * </pre>
 *
 * Protobuf enum {@code registration.REManagementAuthority}
 */
public enum REManagementAuthority
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *&#47; 全体管理者
   * </pre>
   *
   * <code>MP_1 = 0;</code>
   */
  MP_1(0),
  /**
   * <pre>
   *&#47; 所属管理者
   * </pre>
   *
   * <code>MP_2 = 1;</code>
   */
  MP_2(1),
  /**
   * <pre>
   *&#47; なし
   * </pre>
   *
   * <code>MP_3 = 2;</code>
   */
  MP_3(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *&#47; 全体管理者
   * </pre>
   *
   * <code>MP_1 = 0;</code>
   */
  public static final int MP_1_VALUE = 0;
  /**
   * <pre>
   *&#47; 所属管理者
   * </pre>
   *
   * <code>MP_2 = 1;</code>
   */
  public static final int MP_2_VALUE = 1;
  /**
   * <pre>
   *&#47; なし
   * </pre>
   *
   * <code>MP_3 = 2;</code>
   */
  public static final int MP_3_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static REManagementAuthority valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static REManagementAuthority forNumber(int value) {
    switch (value) {
      case 0: return MP_1;
      case 1: return MP_2;
      case 2: return MP_3;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<REManagementAuthority>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      REManagementAuthority> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<REManagementAuthority>() {
          public REManagementAuthority findValueByNumber(int number) {
            return REManagementAuthority.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.getDescriptor().getEnumTypes().get(3);
  }

  private static final REManagementAuthority[] VALUES = values();

  public static REManagementAuthority valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private REManagementAuthority(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:registration.REManagementAuthority)
}

