// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration.proto

package dr.app.core.autogen.grpc.registration;

/**
 * Protobuf enum {@code registration.REOfficeType}
 */
public enum REOfficeType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>MEDICAL = 0;</code>
   */
  MEDICAL(0),
  /**
   * <code>PHARMACY = 1;</code>
   */
  PHARMACY(1),
  /**
   * <code>DRUG_STORE = 2;</code>
   */
  DRUG_STORE(2),
  /**
   * <code>OTHER = 3;</code>
   */
  OTHER(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>MEDICAL = 0;</code>
   */
  public static final int MEDICAL_VALUE = 0;
  /**
   * <code>PHARMACY = 1;</code>
   */
  public static final int PHARMACY_VALUE = 1;
  /**
   * <code>DRUG_STORE = 2;</code>
   */
  public static final int DRUG_STORE_VALUE = 2;
  /**
   * <code>OTHER = 3;</code>
   */
  public static final int OTHER_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static REOfficeType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static REOfficeType forNumber(int value) {
    switch (value) {
      case 0: return MEDICAL;
      case 1: return PHARMACY;
      case 2: return DRUG_STORE;
      case 3: return OTHER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<REOfficeType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      REOfficeType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<REOfficeType>() {
          public REOfficeType findValueByNumber(int number) {
            return REOfficeType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.getDescriptor().getEnumTypes().get(2);
  }

  private static final REOfficeType[] VALUES = values();

  public static REOfficeType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private REOfficeType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:registration.REOfficeType)
}

