// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration_auth.proto

package dr.app.core.autogen.grpc.registration;

/**
 * Protobuf type {@code registration.REOfficeInfo}
 */
public final class REOfficeInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:registration.REOfficeInfo)
    REOfficeInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use REOfficeInfo.newBuilder() to construct.
  private REOfficeInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private REOfficeInfo() {
    officeId_ = "";
    name_ = "";
    officeType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new REOfficeInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private REOfficeInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            officeId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            officeType_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dr.app.core.autogen.grpc.registration.RegistrationAuthOuterClass.internal_static_registration_REOfficeInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dr.app.core.autogen.grpc.registration.RegistrationAuthOuterClass.internal_static_registration_REOfficeInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dr.app.core.autogen.grpc.registration.REOfficeInfo.class, dr.app.core.autogen.grpc.registration.REOfficeInfo.Builder.class);
  }

  public static final int OFFICEID_FIELD_NUMBER = 1;
  private volatile java.lang.Object officeId_;
  /**
   * <code>string officeId = 1;</code>
   * @return The officeId.
   */
  @java.lang.Override
  public java.lang.String getOfficeId() {
    java.lang.Object ref = officeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      officeId_ = s;
      return s;
    }
  }
  /**
   * <code>string officeId = 1;</code>
   * @return The bytes for officeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOfficeIdBytes() {
    java.lang.Object ref = officeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      officeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OFFICETYPE_FIELD_NUMBER = 3;
  private int officeType_;
  /**
   * <code>.registration.REOfficeType officeType = 3;</code>
   * @return The enum numeric value on the wire for officeType.
   */
  @java.lang.Override public int getOfficeTypeValue() {
    return officeType_;
  }
  /**
   * <code>.registration.REOfficeType officeType = 3;</code>
   * @return The officeType.
   */
  @java.lang.Override public dr.app.core.autogen.grpc.registration.REOfficeType getOfficeType() {
    @SuppressWarnings("deprecation")
    dr.app.core.autogen.grpc.registration.REOfficeType result = dr.app.core.autogen.grpc.registration.REOfficeType.valueOf(officeType_);
    return result == null ? dr.app.core.autogen.grpc.registration.REOfficeType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(officeId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, officeId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (officeType_ != dr.app.core.autogen.grpc.registration.REOfficeType.MEDICAL.getNumber()) {
      output.writeEnum(3, officeType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(officeId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, officeId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (officeType_ != dr.app.core.autogen.grpc.registration.REOfficeType.MEDICAL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, officeType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dr.app.core.autogen.grpc.registration.REOfficeInfo)) {
      return super.equals(obj);
    }
    dr.app.core.autogen.grpc.registration.REOfficeInfo other = (dr.app.core.autogen.grpc.registration.REOfficeInfo) obj;

    if (!getOfficeId()
        .equals(other.getOfficeId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (officeType_ != other.officeType_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OFFICEID_FIELD_NUMBER;
    hash = (53 * hash) + getOfficeId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + OFFICETYPE_FIELD_NUMBER;
    hash = (53 * hash) + officeType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dr.app.core.autogen.grpc.registration.REOfficeInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.REOfficeInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REOfficeInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.REOfficeInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REOfficeInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.REOfficeInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REOfficeInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.REOfficeInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REOfficeInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.REOfficeInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.REOfficeInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.REOfficeInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dr.app.core.autogen.grpc.registration.REOfficeInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code registration.REOfficeInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:registration.REOfficeInfo)
      dr.app.core.autogen.grpc.registration.REOfficeInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dr.app.core.autogen.grpc.registration.RegistrationAuthOuterClass.internal_static_registration_REOfficeInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dr.app.core.autogen.grpc.registration.RegistrationAuthOuterClass.internal_static_registration_REOfficeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dr.app.core.autogen.grpc.registration.REOfficeInfo.class, dr.app.core.autogen.grpc.registration.REOfficeInfo.Builder.class);
    }

    // Construct using dr.app.core.autogen.grpc.registration.REOfficeInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      officeId_ = "";

      name_ = "";

      officeType_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dr.app.core.autogen.grpc.registration.RegistrationAuthOuterClass.internal_static_registration_REOfficeInfo_descriptor;
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REOfficeInfo getDefaultInstanceForType() {
      return dr.app.core.autogen.grpc.registration.REOfficeInfo.getDefaultInstance();
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REOfficeInfo build() {
      dr.app.core.autogen.grpc.registration.REOfficeInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REOfficeInfo buildPartial() {
      dr.app.core.autogen.grpc.registration.REOfficeInfo result = new dr.app.core.autogen.grpc.registration.REOfficeInfo(this);
      result.officeId_ = officeId_;
      result.name_ = name_;
      result.officeType_ = officeType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dr.app.core.autogen.grpc.registration.REOfficeInfo) {
        return mergeFrom((dr.app.core.autogen.grpc.registration.REOfficeInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dr.app.core.autogen.grpc.registration.REOfficeInfo other) {
      if (other == dr.app.core.autogen.grpc.registration.REOfficeInfo.getDefaultInstance()) return this;
      if (!other.getOfficeId().isEmpty()) {
        officeId_ = other.officeId_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.officeType_ != 0) {
        setOfficeTypeValue(other.getOfficeTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dr.app.core.autogen.grpc.registration.REOfficeInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dr.app.core.autogen.grpc.registration.REOfficeInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object officeId_ = "";
    /**
     * <code>string officeId = 1;</code>
     * @return The officeId.
     */
    public java.lang.String getOfficeId() {
      java.lang.Object ref = officeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        officeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string officeId = 1;</code>
     * @return The bytes for officeId.
     */
    public com.google.protobuf.ByteString
        getOfficeIdBytes() {
      java.lang.Object ref = officeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        officeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string officeId = 1;</code>
     * @param value The officeId to set.
     * @return This builder for chaining.
     */
    public Builder setOfficeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      officeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string officeId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOfficeId() {
      
      officeId_ = getDefaultInstance().getOfficeId();
      onChanged();
      return this;
    }
    /**
     * <code>string officeId = 1;</code>
     * @param value The bytes for officeId to set.
     * @return This builder for chaining.
     */
    public Builder setOfficeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      officeId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int officeType_ = 0;
    /**
     * <code>.registration.REOfficeType officeType = 3;</code>
     * @return The enum numeric value on the wire for officeType.
     */
    @java.lang.Override public int getOfficeTypeValue() {
      return officeType_;
    }
    /**
     * <code>.registration.REOfficeType officeType = 3;</code>
     * @param value The enum numeric value on the wire for officeType to set.
     * @return This builder for chaining.
     */
    public Builder setOfficeTypeValue(int value) {
      
      officeType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.registration.REOfficeType officeType = 3;</code>
     * @return The officeType.
     */
    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.REOfficeType getOfficeType() {
      @SuppressWarnings("deprecation")
      dr.app.core.autogen.grpc.registration.REOfficeType result = dr.app.core.autogen.grpc.registration.REOfficeType.valueOf(officeType_);
      return result == null ? dr.app.core.autogen.grpc.registration.REOfficeType.UNRECOGNIZED : result;
    }
    /**
     * <code>.registration.REOfficeType officeType = 3;</code>
     * @param value The officeType to set.
     * @return This builder for chaining.
     */
    public Builder setOfficeType(dr.app.core.autogen.grpc.registration.REOfficeType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      officeType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.registration.REOfficeType officeType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOfficeType() {
      
      officeType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:registration.REOfficeInfo)
  }

  // @@protoc_insertion_point(class_scope:registration.REOfficeInfo)
  private static final dr.app.core.autogen.grpc.registration.REOfficeInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dr.app.core.autogen.grpc.registration.REOfficeInfo();
  }

  public static dr.app.core.autogen.grpc.registration.REOfficeInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<REOfficeInfo>
      PARSER = new com.google.protobuf.AbstractParser<REOfficeInfo>() {
    @java.lang.Override
    public REOfficeInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new REOfficeInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<REOfficeInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<REOfficeInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dr.app.core.autogen.grpc.registration.REOfficeInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

