// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration.proto

package dr.app.core.autogen.grpc.registration;

public interface RERoleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registration.RERole)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *&#47; ID
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   *&#47; ID
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   *&#47; ロールコード
   * </pre>
   *
   * <code>string code = 2;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <pre>
   *&#47; ロールコード
   * </pre>
   *
   * <code>string code = 2;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <pre>
   *&#47; ロール名
   * </pre>
   *
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *&#47; ロール名
   * </pre>
   *
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *&#47; ロール表示順
   * </pre>
   *
   * <code>int32 displayOrder = 4;</code>
   * @return The displayOrder.
   */
  int getDisplayOrder();

  /**
   * <pre>
   *&#47; 機能追加日
   * </pre>
   *
   * <code>string added = 5;</code>
   * @return The added.
   */
  java.lang.String getAdded();
  /**
   * <pre>
   *&#47; 機能追加日
   * </pre>
   *
   * <code>string added = 5;</code>
   * @return The bytes for added.
   */
  com.google.protobuf.ByteString
      getAddedBytes();

  /**
   * <pre>
   *&#47; 機能削除日
   * </pre>
   *
   * <code>string deleted = 6;</code>
   * @return The deleted.
   */
  java.lang.String getDeleted();
  /**
   * <pre>
   *&#47; 機能削除日
   * </pre>
   *
   * <code>string deleted = 6;</code>
   * @return The bytes for deleted.
   */
  com.google.protobuf.ByteString
      getDeletedBytes();

  /**
   * <pre>
   *&#47; 機能コード
   * </pre>
   *
   * <code>string functionCode = 7;</code>
   * @return The functionCode.
   */
  java.lang.String getFunctionCode();
  /**
   * <pre>
   *&#47; 機能コード
   * </pre>
   *
   * <code>string functionCode = 7;</code>
   * @return The bytes for functionCode.
   */
  com.google.protobuf.ByteString
      getFunctionCodeBytes();

  /**
   * <pre>
   *&#47; 機能表示順
   * </pre>
   *
   * <code>int32 functionDisplayOrder = 8;</code>
   * @return The functionDisplayOrder.
   */
  int getFunctionDisplayOrder();

  /**
   * <pre>
   *&#47; 作成日時
   * </pre>
   *
   * <code>string created = 9;</code>
   * @return The created.
   */
  java.lang.String getCreated();
  /**
   * <pre>
   *&#47; 作成日時
   * </pre>
   *
   * <code>string created = 9;</code>
   * @return The bytes for created.
   */
  com.google.protobuf.ByteString
      getCreatedBytes();

  /**
   * <pre>
   *&#47; 作成者
   * </pre>
   *
   * <code>string creator = 10;</code>
   * @return The creator.
   */
  java.lang.String getCreator();
  /**
   * <pre>
   *&#47; 作成者
   * </pre>
   *
   * <code>string creator = 10;</code>
   * @return The bytes for creator.
   */
  com.google.protobuf.ByteString
      getCreatorBytes();

  /**
   * <pre>
   *&#47; 更新日時
   * </pre>
   *
   * <code>string updated = 11;</code>
   * @return The updated.
   */
  java.lang.String getUpdated();
  /**
   * <pre>
   *&#47; 更新日時
   * </pre>
   *
   * <code>string updated = 11;</code>
   * @return The bytes for updated.
   */
  com.google.protobuf.ByteString
      getUpdatedBytes();

  /**
   * <pre>
   *&#47; 更新者
   * </pre>
   *
   * <code>string updater = 12;</code>
   * @return The updater.
   */
  java.lang.String getUpdater();
  /**
   * <pre>
   *&#47; 更新者
   * </pre>
   *
   * <code>string updater = 12;</code>
   * @return The bytes for updater.
   */
  com.google.protobuf.ByteString
      getUpdaterBytes();
}
