// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration.proto

package dr.app.core.autogen.grpc.registration;

/**
 * <pre>
 *&#47; ロール
 * </pre>
 *
 * Protobuf type {@code registration.RERole}
 */
public final class RERole extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:registration.RERole)
    RERoleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RERole.newBuilder() to construct.
  private RERole(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RERole() {
    id_ = "";
    code_ = "";
    name_ = "";
    added_ = "";
    deleted_ = "";
    functionCode_ = "";
    created_ = "";
    creator_ = "";
    updated_ = "";
    updater_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RERole();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RERole(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            code_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 32: {

            displayOrder_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            added_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            deleted_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            functionCode_ = s;
            break;
          }
          case 64: {

            functionDisplayOrder_ = input.readInt32();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            created_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            creator_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            updated_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            updater_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.internal_static_registration_RERole_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.internal_static_registration_RERole_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dr.app.core.autogen.grpc.registration.RERole.class, dr.app.core.autogen.grpc.registration.RERole.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   *&#47; ID
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; ID
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object code_;
  /**
   * <pre>
   *&#47; ロールコード
   * </pre>
   *
   * <code>string code = 2;</code>
   * @return The code.
   */
  @java.lang.Override
  public java.lang.String getCode() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; ロールコード
   * </pre>
   *
   * <code>string code = 2;</code>
   * @return The bytes for code.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodeBytes() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   *&#47; ロール名
   * </pre>
   *
   * <code>string name = 3;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; ロール名
   * </pre>
   *
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYORDER_FIELD_NUMBER = 4;
  private int displayOrder_;
  /**
   * <pre>
   *&#47; ロール表示順
   * </pre>
   *
   * <code>int32 displayOrder = 4;</code>
   * @return The displayOrder.
   */
  @java.lang.Override
  public int getDisplayOrder() {
    return displayOrder_;
  }

  public static final int ADDED_FIELD_NUMBER = 5;
  private volatile java.lang.Object added_;
  /**
   * <pre>
   *&#47; 機能追加日
   * </pre>
   *
   * <code>string added = 5;</code>
   * @return The added.
   */
  @java.lang.Override
  public java.lang.String getAdded() {
    java.lang.Object ref = added_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      added_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; 機能追加日
   * </pre>
   *
   * <code>string added = 5;</code>
   * @return The bytes for added.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddedBytes() {
    java.lang.Object ref = added_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      added_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DELETED_FIELD_NUMBER = 6;
  private volatile java.lang.Object deleted_;
  /**
   * <pre>
   *&#47; 機能削除日
   * </pre>
   *
   * <code>string deleted = 6;</code>
   * @return The deleted.
   */
  @java.lang.Override
  public java.lang.String getDeleted() {
    java.lang.Object ref = deleted_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deleted_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; 機能削除日
   * </pre>
   *
   * <code>string deleted = 6;</code>
   * @return The bytes for deleted.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeletedBytes() {
    java.lang.Object ref = deleted_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deleted_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FUNCTIONCODE_FIELD_NUMBER = 7;
  private volatile java.lang.Object functionCode_;
  /**
   * <pre>
   *&#47; 機能コード
   * </pre>
   *
   * <code>string functionCode = 7;</code>
   * @return The functionCode.
   */
  @java.lang.Override
  public java.lang.String getFunctionCode() {
    java.lang.Object ref = functionCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      functionCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; 機能コード
   * </pre>
   *
   * <code>string functionCode = 7;</code>
   * @return The bytes for functionCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFunctionCodeBytes() {
    java.lang.Object ref = functionCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      functionCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FUNCTIONDISPLAYORDER_FIELD_NUMBER = 8;
  private int functionDisplayOrder_;
  /**
   * <pre>
   *&#47; 機能表示順
   * </pre>
   *
   * <code>int32 functionDisplayOrder = 8;</code>
   * @return The functionDisplayOrder.
   */
  @java.lang.Override
  public int getFunctionDisplayOrder() {
    return functionDisplayOrder_;
  }

  public static final int CREATED_FIELD_NUMBER = 9;
  private volatile java.lang.Object created_;
  /**
   * <pre>
   *&#47; 作成日時
   * </pre>
   *
   * <code>string created = 9;</code>
   * @return The created.
   */
  @java.lang.Override
  public java.lang.String getCreated() {
    java.lang.Object ref = created_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      created_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; 作成日時
   * </pre>
   *
   * <code>string created = 9;</code>
   * @return The bytes for created.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCreatedBytes() {
    java.lang.Object ref = created_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      created_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATOR_FIELD_NUMBER = 10;
  private volatile java.lang.Object creator_;
  /**
   * <pre>
   *&#47; 作成者
   * </pre>
   *
   * <code>string creator = 10;</code>
   * @return The creator.
   */
  @java.lang.Override
  public java.lang.String getCreator() {
    java.lang.Object ref = creator_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      creator_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; 作成者
   * </pre>
   *
   * <code>string creator = 10;</code>
   * @return The bytes for creator.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCreatorBytes() {
    java.lang.Object ref = creator_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      creator_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATED_FIELD_NUMBER = 11;
  private volatile java.lang.Object updated_;
  /**
   * <pre>
   *&#47; 更新日時
   * </pre>
   *
   * <code>string updated = 11;</code>
   * @return The updated.
   */
  @java.lang.Override
  public java.lang.String getUpdated() {
    java.lang.Object ref = updated_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      updated_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; 更新日時
   * </pre>
   *
   * <code>string updated = 11;</code>
   * @return The bytes for updated.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpdatedBytes() {
    java.lang.Object ref = updated_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      updated_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATER_FIELD_NUMBER = 12;
  private volatile java.lang.Object updater_;
  /**
   * <pre>
   *&#47; 更新者
   * </pre>
   *
   * <code>string updater = 12;</code>
   * @return The updater.
   */
  @java.lang.Override
  public java.lang.String getUpdater() {
    java.lang.Object ref = updater_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      updater_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; 更新者
   * </pre>
   *
   * <code>string updater = 12;</code>
   * @return The bytes for updater.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpdaterBytes() {
    java.lang.Object ref = updater_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      updater_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (displayOrder_ != 0) {
      output.writeInt32(4, displayOrder_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(added_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, added_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deleted_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, deleted_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(functionCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, functionCode_);
    }
    if (functionDisplayOrder_ != 0) {
      output.writeInt32(8, functionDisplayOrder_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(created_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, created_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(creator_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, creator_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(updated_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, updated_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(updater_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, updater_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    if (displayOrder_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, displayOrder_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(added_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, added_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deleted_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, deleted_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(functionCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, functionCode_);
    }
    if (functionDisplayOrder_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, functionDisplayOrder_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(created_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, created_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(creator_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, creator_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(updated_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, updated_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(updater_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, updater_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dr.app.core.autogen.grpc.registration.RERole)) {
      return super.equals(obj);
    }
    dr.app.core.autogen.grpc.registration.RERole other = (dr.app.core.autogen.grpc.registration.RERole) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getCode()
        .equals(other.getCode())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (getDisplayOrder()
        != other.getDisplayOrder()) return false;
    if (!getAdded()
        .equals(other.getAdded())) return false;
    if (!getDeleted()
        .equals(other.getDeleted())) return false;
    if (!getFunctionCode()
        .equals(other.getFunctionCode())) return false;
    if (getFunctionDisplayOrder()
        != other.getFunctionDisplayOrder()) return false;
    if (!getCreated()
        .equals(other.getCreated())) return false;
    if (!getCreator()
        .equals(other.getCreator())) return false;
    if (!getUpdated()
        .equals(other.getUpdated())) return false;
    if (!getUpdater()
        .equals(other.getUpdater())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DISPLAYORDER_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayOrder();
    hash = (37 * hash) + ADDED_FIELD_NUMBER;
    hash = (53 * hash) + getAdded().hashCode();
    hash = (37 * hash) + DELETED_FIELD_NUMBER;
    hash = (53 * hash) + getDeleted().hashCode();
    hash = (37 * hash) + FUNCTIONCODE_FIELD_NUMBER;
    hash = (53 * hash) + getFunctionCode().hashCode();
    hash = (37 * hash) + FUNCTIONDISPLAYORDER_FIELD_NUMBER;
    hash = (53 * hash) + getFunctionDisplayOrder();
    hash = (37 * hash) + CREATED_FIELD_NUMBER;
    hash = (53 * hash) + getCreated().hashCode();
    hash = (37 * hash) + CREATOR_FIELD_NUMBER;
    hash = (53 * hash) + getCreator().hashCode();
    hash = (37 * hash) + UPDATED_FIELD_NUMBER;
    hash = (53 * hash) + getUpdated().hashCode();
    hash = (37 * hash) + UPDATER_FIELD_NUMBER;
    hash = (53 * hash) + getUpdater().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dr.app.core.autogen.grpc.registration.RERole parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.RERole parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.RERole parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.RERole parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.RERole parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dr.app.core.autogen.grpc.registration.RERole parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.RERole parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.RERole parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.RERole parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.RERole parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dr.app.core.autogen.grpc.registration.RERole parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dr.app.core.autogen.grpc.registration.RERole parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dr.app.core.autogen.grpc.registration.RERole prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *&#47; ロール
   * </pre>
   *
   * Protobuf type {@code registration.RERole}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:registration.RERole)
      dr.app.core.autogen.grpc.registration.RERoleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.internal_static_registration_RERole_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.internal_static_registration_RERole_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dr.app.core.autogen.grpc.registration.RERole.class, dr.app.core.autogen.grpc.registration.RERole.Builder.class);
    }

    // Construct using dr.app.core.autogen.grpc.registration.RERole.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      code_ = "";

      name_ = "";

      displayOrder_ = 0;

      added_ = "";

      deleted_ = "";

      functionCode_ = "";

      functionDisplayOrder_ = 0;

      created_ = "";

      creator_ = "";

      updated_ = "";

      updater_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dr.app.core.autogen.grpc.registration.RegistrationOuterClass.internal_static_registration_RERole_descriptor;
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.RERole getDefaultInstanceForType() {
      return dr.app.core.autogen.grpc.registration.RERole.getDefaultInstance();
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.RERole build() {
      dr.app.core.autogen.grpc.registration.RERole result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dr.app.core.autogen.grpc.registration.RERole buildPartial() {
      dr.app.core.autogen.grpc.registration.RERole result = new dr.app.core.autogen.grpc.registration.RERole(this);
      result.id_ = id_;
      result.code_ = code_;
      result.name_ = name_;
      result.displayOrder_ = displayOrder_;
      result.added_ = added_;
      result.deleted_ = deleted_;
      result.functionCode_ = functionCode_;
      result.functionDisplayOrder_ = functionDisplayOrder_;
      result.created_ = created_;
      result.creator_ = creator_;
      result.updated_ = updated_;
      result.updater_ = updater_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dr.app.core.autogen.grpc.registration.RERole) {
        return mergeFrom((dr.app.core.autogen.grpc.registration.RERole)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dr.app.core.autogen.grpc.registration.RERole other) {
      if (other == dr.app.core.autogen.grpc.registration.RERole.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getDisplayOrder() != 0) {
        setDisplayOrder(other.getDisplayOrder());
      }
      if (!other.getAdded().isEmpty()) {
        added_ = other.added_;
        onChanged();
      }
      if (!other.getDeleted().isEmpty()) {
        deleted_ = other.deleted_;
        onChanged();
      }
      if (!other.getFunctionCode().isEmpty()) {
        functionCode_ = other.functionCode_;
        onChanged();
      }
      if (other.getFunctionDisplayOrder() != 0) {
        setFunctionDisplayOrder(other.getFunctionDisplayOrder());
      }
      if (!other.getCreated().isEmpty()) {
        created_ = other.created_;
        onChanged();
      }
      if (!other.getCreator().isEmpty()) {
        creator_ = other.creator_;
        onChanged();
      }
      if (!other.getUpdated().isEmpty()) {
        updated_ = other.updated_;
        onChanged();
      }
      if (!other.getUpdater().isEmpty()) {
        updater_ = other.updater_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dr.app.core.autogen.grpc.registration.RERole parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dr.app.core.autogen.grpc.registration.RERole) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <pre>
     *&#47; ID
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; ID
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; ID
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ID
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ID
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object code_ = "";
    /**
     * <pre>
     *&#47; ロールコード
     * </pre>
     *
     * <code>string code = 2;</code>
     * @return The code.
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; ロールコード
     * </pre>
     *
     * <code>string code = 2;</code>
     * @return The bytes for code.
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; ロールコード
     * </pre>
     *
     * <code>string code = 2;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ロールコード
     * </pre>
     *
     * <code>string code = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      
      code_ = getDefaultInstance().getCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ロールコード
     * </pre>
     *
     * <code>string code = 2;</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      code_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *&#47; ロール名
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; ロール名
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; ロール名
     * </pre>
     *
     * <code>string name = 3;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ロール名
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ロール名
     * </pre>
     *
     * <code>string name = 3;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int displayOrder_ ;
    /**
     * <pre>
     *&#47; ロール表示順
     * </pre>
     *
     * <code>int32 displayOrder = 4;</code>
     * @return The displayOrder.
     */
    @java.lang.Override
    public int getDisplayOrder() {
      return displayOrder_;
    }
    /**
     * <pre>
     *&#47; ロール表示順
     * </pre>
     *
     * <code>int32 displayOrder = 4;</code>
     * @param value The displayOrder to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayOrder(int value) {
      
      displayOrder_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; ロール表示順
     * </pre>
     *
     * <code>int32 displayOrder = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayOrder() {
      
      displayOrder_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object added_ = "";
    /**
     * <pre>
     *&#47; 機能追加日
     * </pre>
     *
     * <code>string added = 5;</code>
     * @return The added.
     */
    public java.lang.String getAdded() {
      java.lang.Object ref = added_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        added_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; 機能追加日
     * </pre>
     *
     * <code>string added = 5;</code>
     * @return The bytes for added.
     */
    public com.google.protobuf.ByteString
        getAddedBytes() {
      java.lang.Object ref = added_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        added_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; 機能追加日
     * </pre>
     *
     * <code>string added = 5;</code>
     * @param value The added to set.
     * @return This builder for chaining.
     */
    public Builder setAdded(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      added_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 機能追加日
     * </pre>
     *
     * <code>string added = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdded() {
      
      added_ = getDefaultInstance().getAdded();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 機能追加日
     * </pre>
     *
     * <code>string added = 5;</code>
     * @param value The bytes for added to set.
     * @return This builder for chaining.
     */
    public Builder setAddedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      added_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deleted_ = "";
    /**
     * <pre>
     *&#47; 機能削除日
     * </pre>
     *
     * <code>string deleted = 6;</code>
     * @return The deleted.
     */
    public java.lang.String getDeleted() {
      java.lang.Object ref = deleted_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deleted_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; 機能削除日
     * </pre>
     *
     * <code>string deleted = 6;</code>
     * @return The bytes for deleted.
     */
    public com.google.protobuf.ByteString
        getDeletedBytes() {
      java.lang.Object ref = deleted_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deleted_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; 機能削除日
     * </pre>
     *
     * <code>string deleted = 6;</code>
     * @param value The deleted to set.
     * @return This builder for chaining.
     */
    public Builder setDeleted(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deleted_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 機能削除日
     * </pre>
     *
     * <code>string deleted = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeleted() {
      
      deleted_ = getDefaultInstance().getDeleted();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 機能削除日
     * </pre>
     *
     * <code>string deleted = 6;</code>
     * @param value The bytes for deleted to set.
     * @return This builder for chaining.
     */
    public Builder setDeletedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deleted_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object functionCode_ = "";
    /**
     * <pre>
     *&#47; 機能コード
     * </pre>
     *
     * <code>string functionCode = 7;</code>
     * @return The functionCode.
     */
    public java.lang.String getFunctionCode() {
      java.lang.Object ref = functionCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        functionCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; 機能コード
     * </pre>
     *
     * <code>string functionCode = 7;</code>
     * @return The bytes for functionCode.
     */
    public com.google.protobuf.ByteString
        getFunctionCodeBytes() {
      java.lang.Object ref = functionCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        functionCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; 機能コード
     * </pre>
     *
     * <code>string functionCode = 7;</code>
     * @param value The functionCode to set.
     * @return This builder for chaining.
     */
    public Builder setFunctionCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      functionCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 機能コード
     * </pre>
     *
     * <code>string functionCode = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearFunctionCode() {
      
      functionCode_ = getDefaultInstance().getFunctionCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 機能コード
     * </pre>
     *
     * <code>string functionCode = 7;</code>
     * @param value The bytes for functionCode to set.
     * @return This builder for chaining.
     */
    public Builder setFunctionCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      functionCode_ = value;
      onChanged();
      return this;
    }

    private int functionDisplayOrder_ ;
    /**
     * <pre>
     *&#47; 機能表示順
     * </pre>
     *
     * <code>int32 functionDisplayOrder = 8;</code>
     * @return The functionDisplayOrder.
     */
    @java.lang.Override
    public int getFunctionDisplayOrder() {
      return functionDisplayOrder_;
    }
    /**
     * <pre>
     *&#47; 機能表示順
     * </pre>
     *
     * <code>int32 functionDisplayOrder = 8;</code>
     * @param value The functionDisplayOrder to set.
     * @return This builder for chaining.
     */
    public Builder setFunctionDisplayOrder(int value) {
      
      functionDisplayOrder_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 機能表示順
     * </pre>
     *
     * <code>int32 functionDisplayOrder = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearFunctionDisplayOrder() {
      
      functionDisplayOrder_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object created_ = "";
    /**
     * <pre>
     *&#47; 作成日時
     * </pre>
     *
     * <code>string created = 9;</code>
     * @return The created.
     */
    public java.lang.String getCreated() {
      java.lang.Object ref = created_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        created_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; 作成日時
     * </pre>
     *
     * <code>string created = 9;</code>
     * @return The bytes for created.
     */
    public com.google.protobuf.ByteString
        getCreatedBytes() {
      java.lang.Object ref = created_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        created_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; 作成日時
     * </pre>
     *
     * <code>string created = 9;</code>
     * @param value The created to set.
     * @return This builder for chaining.
     */
    public Builder setCreated(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      created_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 作成日時
     * </pre>
     *
     * <code>string created = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreated() {
      
      created_ = getDefaultInstance().getCreated();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 作成日時
     * </pre>
     *
     * <code>string created = 9;</code>
     * @param value The bytes for created to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      created_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object creator_ = "";
    /**
     * <pre>
     *&#47; 作成者
     * </pre>
     *
     * <code>string creator = 10;</code>
     * @return The creator.
     */
    public java.lang.String getCreator() {
      java.lang.Object ref = creator_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creator_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; 作成者
     * </pre>
     *
     * <code>string creator = 10;</code>
     * @return The bytes for creator.
     */
    public com.google.protobuf.ByteString
        getCreatorBytes() {
      java.lang.Object ref = creator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; 作成者
     * </pre>
     *
     * <code>string creator = 10;</code>
     * @param value The creator to set.
     * @return This builder for chaining.
     */
    public Builder setCreator(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      creator_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 作成者
     * </pre>
     *
     * <code>string creator = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreator() {
      
      creator_ = getDefaultInstance().getCreator();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 作成者
     * </pre>
     *
     * <code>string creator = 10;</code>
     * @param value The bytes for creator to set.
     * @return This builder for chaining.
     */
    public Builder setCreatorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      creator_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object updated_ = "";
    /**
     * <pre>
     *&#47; 更新日時
     * </pre>
     *
     * <code>string updated = 11;</code>
     * @return The updated.
     */
    public java.lang.String getUpdated() {
      java.lang.Object ref = updated_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updated_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; 更新日時
     * </pre>
     *
     * <code>string updated = 11;</code>
     * @return The bytes for updated.
     */
    public com.google.protobuf.ByteString
        getUpdatedBytes() {
      java.lang.Object ref = updated_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updated_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; 更新日時
     * </pre>
     *
     * <code>string updated = 11;</code>
     * @param value The updated to set.
     * @return This builder for chaining.
     */
    public Builder setUpdated(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      updated_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 更新日時
     * </pre>
     *
     * <code>string updated = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdated() {
      
      updated_ = getDefaultInstance().getUpdated();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 更新日時
     * </pre>
     *
     * <code>string updated = 11;</code>
     * @param value The bytes for updated to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      updated_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object updater_ = "";
    /**
     * <pre>
     *&#47; 更新者
     * </pre>
     *
     * <code>string updater = 12;</code>
     * @return The updater.
     */
    public java.lang.String getUpdater() {
      java.lang.Object ref = updater_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updater_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; 更新者
     * </pre>
     *
     * <code>string updater = 12;</code>
     * @return The bytes for updater.
     */
    public com.google.protobuf.ByteString
        getUpdaterBytes() {
      java.lang.Object ref = updater_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updater_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; 更新者
     * </pre>
     *
     * <code>string updater = 12;</code>
     * @param value The updater to set.
     * @return This builder for chaining.
     */
    public Builder setUpdater(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      updater_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 更新者
     * </pre>
     *
     * <code>string updater = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdater() {
      
      updater_ = getDefaultInstance().getUpdater();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; 更新者
     * </pre>
     *
     * <code>string updater = 12;</code>
     * @param value The bytes for updater to set.
     * @return This builder for chaining.
     */
    public Builder setUpdaterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      updater_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:registration.RERole)
  }

  // @@protoc_insertion_point(class_scope:registration.RERole)
  private static final dr.app.core.autogen.grpc.registration.RERole DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dr.app.core.autogen.grpc.registration.RERole();
  }

  public static dr.app.core.autogen.grpc.registration.RERole getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RERole>
      PARSER = new com.google.protobuf.AbstractParser<RERole>() {
    @java.lang.Override
    public RERole parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RERole(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RERole> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RERole> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dr.app.core.autogen.grpc.registration.RERole getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

