// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration_auth.proto

package dr.app.core.autogen.grpc.registration;

public interface REUserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registration.REUserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string officeUserId = 2;</code>
   * @return The officeUserId.
   */
  java.lang.String getOfficeUserId();
  /**
   * <code>string officeUserId = 2;</code>
   * @return The bytes for officeUserId.
   */
  com.google.protobuf.ByteString
      getOfficeUserIdBytes();

  /**
   * <code>.registration.REOfficeType officeType = 3;</code>
   * @return The enum numeric value on the wire for officeType.
   */
  int getOfficeTypeValue();
  /**
   * <code>.registration.REOfficeType officeType = 3;</code>
   * @return The officeType.
   */
  dr.app.core.autogen.grpc.registration.REOfficeType getOfficeType();

  /**
   * <code>string firstName = 4;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 4;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 5;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 5;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();
}
