service:
  port-range: 8010_8019

## Spring configuration
spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_SERVER:localhost}:${MONGODB_SERVER_PORT:27017}/db_calculator
  rabbitmq:
    host: ${RABBITMQ_SERVER:localhost}
    username: user
    password: bitnami
    port: 5672
  application:
    name: service-calculator

## RabbitMQ configuration
multiplication:
  exchange: multiplication_exchange
  solved:
    key: multiplication.solved

# Service Discovery configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

## Log configuration
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate=DEBUG: